### ISSUE TITLE
Bootsnap changes YAML.load_file's accepted args

### ISSUE THREAD

**Issue by dannyfallon** [Shopify/bootsnap#124]
:wave: The Ruby docs for `YAML.load_file` specifies a `filepath` as the argument. This then calls `File.open(filepath)` and calls `YAML.load` on the file object. However, `filepath` is not required to be a string -  you can also pass in a File Object instead of a path and it works perfectly fine in a non-Bootsnap codebase:

```ruby
> f = File.open('/tmp/test.yml')
=> #<File:/tmp/test.yml>
> YAML.load_file('/tmp/test.yml')
=> {"environment"=>"test"}
> YAML.load_file(f)
=> {"environment"=>"test"}
```

But with Bootsnap enabled:

```ruby
> f = File.open('/tmp/test.yml')
=> #<File:/tmp/test.yml>
> YAML.load_file('/tmp/test.yml')
=> {"environment"=>"test"}
> YAML.load_file(f)
Errno::ENOENT: No such file or directory - bs_fetch:open_current_file:open
from /Users/danny/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bootsnap-1.1.8/lib/bootsnap/compile_cache/yaml.rb:50:in `fetch'
```

When we overload `YAML.load_file` in [`Bootsnap::CompileCache::YAML`](https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/compile_cache/yaml.rb#L51), we assume `path` is a string and pass `path.to_s` down to `Bootsnap::CompileCache::Native.fetch`. Calling `path.to_s` on a File object give an invalid file path, hence the error.

```ruby
> f.to_s
=> "#<File:0x007fec1dddf980>"
```

We've already updated our code to use a string into `YAML.load_file` to unblock ourselves but the behaviour was surprising enough that I'm willing to try to fix it. Would you be interested in a PR that uses `File.path` instead of `path.to_s` for calling down to `Bootsnap::CompileCache::Native.fetch` when a file object is passed in `YAML.load_file`? This would restore the behaviour we were seeing before installing Bootsnap

**Comment by stevenharman** [comment]
We stumbled on this as well. We have a spec support module that we use to make `I18n` translations available for isolated specs - where Rails is not loaded:

```ruby
module I18nHelpers
  def self.included(_mod)
    locale_dir = Pathname.new(__dir__) + '../../config/locales/'
    [:en].each do |locale|
      binding.pry
      locale_file = locale_dir + "#{locale}.yml"
      I18n.backend.store_translations(locale, YAML.load_file(locale_file.open)[String(locale)])
    end
  end
end
```

We have a `Pathname` object, which we `#open` and pass to `YAML.load_file`. Meaning we're passing File object. We'll update that to instead pass the file path as a string.

**Comment by envygeeks** [comment]
You should be using `#to_path` not `#path`, any object that has `#to_path` is accepted by stdlib, not `#path`, actually any method that deals with the filesystem should first check for `#to_path` and then fallback to `#to_s`.  Just like stdlib would. This works with your own homegrown classes, and even throughout stdlib as a consistency.

```ruby
class MyClass
  def initialize(a)
    @a = a
  end  
  
  def to_path
    @a
  end  
end  

File.readlines(MyClass.new("blocklist.txt")).first
# => "0.r.msn.com\n"
```

**Comment by stevenharman** [comment]
> You should be using #to_path not #path, any object that has #to_path is accepted by stdlib

Indeed. This is exactly the protocol used by `Pathname`, which we were using.

**Comment by dannyfallon** [comment]
Closed by https://github.com/Shopify/bootsnap/pull/186

**Comment by davismattg** [comment]
I had this issue after upgrading to Rails 6.0.3.3. For me, even using a string did not work:
```
# config/initializers/client_apps.rb
ClientApps = YAML.load_file('/config/client_apps.yml')[Rails.env] # would not start Rails server
```

What did work was using Rails' `config_for` helper:
```
# config/initializers/client_apps.rb
ClientApps = Rails.application.config_for(:client_apps)
```
