### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by headius** [Shopify/bootsnap#129]
This library is a dependency of Discourse, which I am trying to get running on JRuby. However JRuby does not support CRuby extensions.

The library doesn't look very big, and should be a straightforward port. Perhaps we can work together to add JRuby support to bootsnap?

**Comment by burke** [comment]
Sure, happy to support JRuby, but I have no experience with it. I assumed there was no corresponding API for ISeq caching but thinking about it now it seems obvious that it should be possible.

**Comment by headius** [comment]
I noticed there's a -java version of the gem now, which lets it install on JRuby. That satisfies me, even if it's not getting the most out of the other features of bootsnap. Perhaps we could call this issue done and open others for missing features?

**Comment by burke** [comment]
Migrated to https://github.com/Shopify/bootsnap/issues/164
