### ISSUE TITLE
compile_cache_iseq and compile_cache_yaml on Linux

### ISSUE THREAD

**Issue by SamSaffron** [Shopify/bootsnap#14]
I wanted to open a placeholder topic for getting support for `compile_cache_iseq` and `compile_cache_yaml` on Linux. 

In general (when I am not travelling) Linux is my dev box so I would love to have everything working there. 

What are the blockers here? What needs to be implemented?

**Comment by burke** [comment]
The code right now uses extended filesystem attributes on the source files as the cache backend. The code actually supports linux in a "theoretically it might work" kind of way, but linux doesn't mount volumes with `-o user_xattr` by default. It's totally possible it would work with 0-5 lines changed on a volume with `user_xattr`.

Probably the compile_cache stuff should be rewritten to use some other backend. I couldn't find anything as fast as this, but I'd trade a few ms for broader compatibility.

**Comment by SamSaffron** [comment]
Hmm, brainstorming, what about an optional redis or memcached store?

**Comment by burke** [comment]
I'm pretty sure the network overhead would kill it. I tried it with [lmdb](https://github.com/minad/lmdb) which basically `mmap`s a b-tree in and returns values as strings without copying them out of the mmap'd region. That was a tiny bit slower than this on read, and quite a lot slower on insert. Redis and memcached would be at best comparable to this, but with additional network overhead.

It probably makes sense to just have an alternate strategy that uses a cache directory, like `tmp/cache/bootsnap-compile-cache/de/deadbeefcafe00042` or whatever, maybe key it on md5sum of the filename or something. This would be more container-friendly too.

**Comment by wjordan** [comment]
> I tried it with lmdb which basically mmaps a b-tree in and returns values as strings without copying them out of the mmap'd region. That was somewhat slower than this on read, and quite a lot slower on insert.

The [lmdb](https://github.com/minad/lmdb) gem seems to have _terrible_ write performance, according to [moneta](https://github.com/minad/moneta)'s CI benchmarks (and my own ad-hoc tests)- one [example benchmark run](https://travis-ci.org/minad/moneta/jobs/228354777) shows only **~700** write ops/sec compared to **~160k** ops/sec for [LocalMemCache](https://github.com/sck/localmemcache) in the same test, or **> 200x** faster).

> Redis and memcached would be at best comparable to this, but with additional network overhead.

The same benchmark shows `Redis` and `MemcachedDalli` both achieving **~11k** ops/sec, which is **~15x** faster than `lmdb`'s performance. Even basic `File` storage achieved **8500** ops/sec.

With orders-of-magnitude variations like this, I wouldn't be surprised if you saw much different results using a different cache implementation from `lmdb`.

> It probably makes sense to just have an alternate strategy that uses a cache directory, like `tmp/cache/bootsnap-compile-cache/de/deadbeefcafe00042` or whatever, maybe key it on md5sum of the filename or something. This would be more container-friendly too.

I think it would make sense to just extract the cache implementation entirely from this library, so the user can mix and match existing implementations according to their use-case (optionally with a default implementation that can be easily overridden). See #25 for a PR going in this direction.

**Comment by burke** [comment]
> LocalMemCache

I'm kind of shocked I've never found this; I've basically googled for those exact words a dozen times over the years.

**Comment by SamSaffron** [comment]
@wjordan very much appreciate having a clean interface here, but I think that ideally there should be native implementations so you don't create a minimum of 1 extra RVALUEs per cache hit and do a bunch or work in ruby land.  

At a minimum if the interface is going to allow a "ruby" interface it should be:

```
GenericISeqCache
   def get(key)
     #return RubyVM::InstructionSequence
    end
    ... etc .. 
end
```

**Comment by wjordan** [comment]
The current implementation calls out to Ruby to load the compiled code ([`RubyVM::InstructionSequence.load_from_binary(binary)`](https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/compile_cache/iseq.rb#L14)), which already requires a redundant Ruby string allocation. A Ruby cache interface wouldn't be any worse off than the current implementation. Besides, I'd expect the cost of a single extra string allocation per cache-hit to be small relative to filesystem I/O (checking the file's mtime, at minimum).

Also, many performance-oriented cache implementations are implemented via C extensions so the 'work' of a cache implementation wouldn't necessarily performed in ruby-land either.

**Comment by SamSaffron** [comment]
@wjordan yeah you are right there, in fact there is no direct way to load up an instruction sequence from a buffer even if we wanted to

https://bugs.ruby-lang.org/issues/13544

**Comment by burke** [comment]
I have a branch started that migrates from xattrs to a less exotic strategy that will work on linux: https://github.com/Shopify/bootsnap/pull/43

**Comment by burke** [comment]
0.3.0. released
