### ISSUE TITLE
Rails boot failure when cache dir isn't writable

### ISSUE THREAD

**Issue by zorab47** [Shopify/bootsnap#144]
Rails boot fails when cache dir isn't writable. Should it fail gracefully when unable to write cache files?

### Steps to Reproduce

1. Create a readonly directory
  ```sh
  mkdir -p -m 0555 tmp/readonly
  ```
2. Configure Bootsnap to use the readonly directory
  ```ruby
  # config/boot.rb

  require 'bootsnap'
  Bootsnap.setup(
    cache_dir: 'tmp/readonly'
  )
  ```
3. Execute a Rails command
  ```sh
  bundle exec rails console
  ```

### Error

That raises an error when Bootsnap tries to write into the directory.

```sh
$ bundle exec rails console
# ...
~/Code/test-app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/store.rb:77:in `binwrite': Permission denied @ rb_sysopen - tmp/readonly/bootsnap-load-path-cache.29785.39297.tmp (Errno::EACCES)
```

### Reasoning

Several of the apps I work on use read-only docker images in production (specifically in the case of workers). I'd suggest that Bootsnap logs a warning in this situation rather than failing to boot.

**Comment by burke** [comment]
I think this is probably the behaviour we should keep: it's pretty normal to expect a writable cache dir and I don't like how easy it would be to not notice if we would keep booting anyway. There's nothing bootsnap can do when it's not able to cache files, so I'd recommend instead wrapping the setup in a conditional to just prevent it from being loaded at all in this environment.

(sorry for the incredibly long delay in response!)

**Comment by zorab47** [comment]
I understand. Might I still suggest a warning in the Readme about potential failure scenario?

**Comment by burke** [comment]
Yeah, that's a good idea. Done in bc2b892ff3db50da0322838e72cfa54d38ee6040.
