### ISSUE TITLE
Bootsnap never prunes the compile cache

### ISSUE THREAD

**Issue by burke** [Shopify/bootsnap#154]
https://github.com/Shopify/bootsnap/issues/153

**Comment by inopinatus** [comment]
ideally a rake task that only prunes stale files a la `assets:clean`

**Comment by burke** [comment]
I think we'll continue to leave this to the user to figure out for now.

We'd happily accept PRs to make this more clear in documentation.

We'd possibly be ok with PRs to implement automatic cleanup.
