### ISSUE TITLE
Cache Read Failure If Cache Key Ends With Underscore

### ISSUE THREAD

**Issue by jasonivers** [Shopify/bootsnap#155]
After adding bootsnap to my app (ruby 2.5.1, rails 5.2), attempting to read cache keys that end in _ cause this error:

NameError: uninitialized constant ActiveRecord::AttributeSet
from /my/app/shared/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'

Removing the _ from the end of the cache key prevents the error.

**Comment by jasonivers** [comment]
Actually, I misunderstood what the error was... Previously I was able to cache an initialized serializer (i.e. with the data in it), and have it work as caching anything else.  I am no longer able to do that, and must first convert it to JSON, then to a hash, to make it work... going straight to a hash does not work either, with an error about dumping an anonymous class (and given my specific usage, storing it directly as JSON doesn't make sense).

**Comment by burke** [comment]
I don't think I understand the issue fully but regardless, this is crazy stale. Sorry I never got around to responding, feel free to reopen if there's still a problem.
