### ISSUE TITLE
Incompatible Library Version - Mac

### ISSUE THREAD

**Issue by jasonivers** [Shopify/bootsnap#158]
When I try to run migrations locally on a Macbook Pro (10.13.4), I get this:

rake db:migrate VERSION=0
rake aborted!
LoadError: incompatible library version - /Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/bootsnap.bundle
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:1:in `<top (required)>'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache.rb:5:in `setup'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap.rb:30:in `setup'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/bootsnap-1.3.0/lib/bootsnap/setup.rb:33:in `<top (required)>'
/Users/myuser/myapp/config/boot.rb:4:in `require'
/Users/myuser/myapp/config/boot.rb:4:in `<top (required)>'
/Users/myuser/myapp/config/application.rb:1:in `require'
/Users/myuser/myapp/config/application.rb:1:in `<top (required)>'
/Users/myuser/myapp/Rakefile:5:in `require'
/Users/myuser/myapp/Rakefile:5:in `<top (required)>'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/bin/ruby_executable_hooks:15:in `eval'
/Users/myuser/.rvm/gems/ruby-2.5.1@myapp/bin/ruby_executable_hooks:15:in `<main>'

Everything seems to be working properly on a remote Linux server.

**Comment by jasonivers** [comment]
There was an issue with rvm.  I needed to do:
```
rvm gemset empty
gem install bundler
bundle install
```

**Comment by chnoack** [comment]
I had the same after switching from RVM to ASDF.  I did the following to solve it:

- _gem pristine --all_
- in my project's folder:  _rm -rf vendor_ (removes the project specific gem folder)
- _bundle update_
