### ISSUE TITLE
Bootsnap breaks loading all internal JRuby extensions

### ISSUE THREAD

**Issue by headius** [Shopify/bootsnap#162]
We discovered today (release day for 9.1.17.0...grumble) that bootsnap is broken on JRuby, which breaks any rails apps using it. The problem appears to be that bootsnap refuses to load any files which it cannot find physically on the filesystem. JRuby ships a number of libraries within its .jar archive, so they would not be visible to bootsnap. In addition, many of our core extensions are "virtual" in that we register a loadable entry for them but they do not exist as a .jar (or .so or .dll) anywhere in the system.

The error manifests like this:

```
$ jruby   -S rails server
NameError: uninitialized constant CGI::Util::Escape
                       const_missing at org/jruby/RubyModule.java:3370
                       <module:Util> at /Users/headius/projects/jruby/lib/ruby/stdlib/cgi/util.rb:10
                         <class:CGI> at /Users/headius/projects/jruby/lib/ruby/stdlib/cgi/util.rb:9
                              <main> at /Users/headius/projects/jruby/lib/ruby/stdlib/cgi/util.rb:8
                             require at org/jruby/RubyKernel.java:956
                     block in (root) at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:1
           require_with_bootsnap_lfi at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21
                            register at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
           require_with_bootsnap_lfi at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20
                              <main> at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29
                             require at org/jruby/RubyKernel.java:956
```

The actual problem, hidden by cgi.rb's load of cgi/escape, is a cryptic error from bootsnap:

```
#<Class:0x4066c471>: cannot load such file -- cgi/escape
                             require at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
                              <main> at /Users/headius/projects/jruby/lib/ruby/stdlib/cgi/util.rb:5
                             require at org/jruby/RubyKernel.java:956
                     block in (root) at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:1
           require_with_bootsnap_lfi at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21
                            register at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
           require_with_bootsnap_lfi at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20
                              <main> at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/bootsnap-1.3.0-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29
                             require at org/jruby/RubyKernel.java:956
```

Bootsnap should not assume all files that will be loaded exist on the filesystem, because there are at least two implementations for which that might not be the case.

**Comment by headius** [comment]
This is a very high priority for us to get fixed, since all recent Rails versions (5.0, 5.1, 5.2) all now require bootsnap when generating a new app.

**Comment by headius** [comment]
Sorry I may have been mistaken about the versions of Rails that require bootsnap. I can only confirm that 5.2 requires it.

**Comment by headius** [comment]
And this is not limited to bootsnap 1.3.0. I confirmed it is also broken in 1.2.1.

**Comment by headius** [comment]
Removing bootsnap from Gemfile and config/boot.rb allows Rails to start up properly.

**Comment by burke** [comment]
This is how we solve this for MRI's builtin `enumerator.so`, etc.: https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/load_path_cache/cache.rb#L25-L41

Do you think we can make some variant of this work for JRuby?

**Comment by headius** [comment]
Hmm...well that would work for *some* of the exts if we also added ".jar" to the matching, but there exts that have paths *and* are internal for JRuby.

The complete list of exts we register are here...

[JRuby 9.1.x](https://github.com/jruby/jruby/blob/5ce4034a5f39f445c29036880f6a552f6b5421d6/core/src/main/java/org/jruby/Ruby.java#L1682-L1741)

[JRuby 9.2.x](https://github.com/jruby/jruby/blob/333a45e659dea2e7651b9ccc4df81500dcf0d5a0/core/src/main/java/org/jruby/Ruby.java#L1568-L1620)

Why does bootsnap raise the error rather than just letting the standard require take over?

**Comment by headius** [comment]
> I don't really understand the details of this, so I'm not sure how we might accommodate them

Well, for example, this extension is "cgi/escape.jar" but it's internal...there is no jar file in the system.

For what it's worth I applaud what you're doing here with load path caching, and I'd love to see something like this become standard behavior for require. We just need to allow this mechanism to continue working for JRuby's internal extensions.

**Comment by headius** [comment]
In case I wasn't clear, I meant that [this line] will prevent some JRuby internal exts from loading.

Here is a (better) complete list of exts that JRuby 9.1 or 9.2 have internally:

* "java.rb"
* "jruby.rb"
* "jruby/util.rb"
* "jruby/type.rb"
* "nkf.jar"
* "stringio.jar"
* "strscan.jar"
* "zlib.jar"
* "thread.jar"
* "thread.rb"
* "digest.jar"
* "digest/md5.jar"
* "digest/rmd160.jar"
* "digest/sha1.jar"
* "digest/sha2.jar"
* "digest/bubblebabble.jar"
* "bigdecimal.jar"
* "io/wait.jar"
* "etc.jar"
* "timeout.rb"
* "socket.jar"
* "rbconfig.rb"
* "jruby/serialization.rb"
* "ffi-internal.jar"
* "tempfile.jar"
* "fcntl.rb"
* "pathname.jar"
* "mathn/complex.jar"
* "mathn/rational.jar"
* "ripper.jar"
* "coverage.jar"
* "continuation.rb"
* "enumerator.jar" (though this and complex.jar and rational.jar are in LOADED_FEATURES at boot).
* "thread.rb"
* "net/protocol.rb"
* "win32ole.jar"
* "cgi/escape.jar"

I have concerns about just adding these to a list; it ties our hands when we want to add a new one. Perhaps we can add a method that you could query to get an updated list of builtin extensions? We could have a list as a fallback when that method isn't present (which would cover all historical JRuby releases).

**Comment by headius** [comment]
Seems I missed some. JRuby master will shortly have the JRuby::Util.internal_libraries method. It was possible to get at it without a standard feature, but having it standard will be more reliable.

There's also a "net/protocol.rb" library that's disabled by default, but I think we're going to be removing it (and nobody is using our ext version of it anyway).

```
$ jruby -e 'require "jruby/util"; puts JRuby::Util.internal_libraries'
nkf.jar
complex.jar
jruby/util.rb
digest/bubblebabble.jar
timeout.rb
digest/sha2.jar
pathname.jar
jruby/serialization.rb
jruby/type.rb
strscan.jar
enumerator.jar
digest/sha1.jar
etc.jar
mathn/complex.jar
stringio.jar
date.jar
continuation.rb
digest.jar
digest/rmd160.jar
cgi/escape.jar
jruby.rb
zlib.jar
rational.jar
ripper.jar
bigdecimal.jar
socket.jar
win32ole.jar
rbconfig.rb
io/wait.jar
mathn/rational.jar
coverage.jar
thread.rb
digest/md5.jar
java.rb
ffi-internal.jar
tempfile.jar
set.rb
fcntl.rb
```

**Comment by headius** [comment]
Oh, there is another situation we need to consider: JRuby can be packaged up, with an app and all its dependencies, inside a jar file...and run directly from the jar file without expanding on the filesystem. This means that ALL bootsnap searches might fail from within a jar.

When loading from within the jar, resources will have a URI path something like "uri:classloader:/stdlib/net/http.rb" or "jar:file:some/path/to/some.jar!some/file/path/in/jar.rb". Most of our File-related methods are designed to work with these URIs but not all of them.

And yes, JRuby load path can contain jar files, classloader URIs, etc.

**Comment by kamal-kambe** [comment]
I'm facing the same issue. Is there any workaround/fix for this yet?

**Comment by minmay** [comment]
I hope this get fixed soon. I tried to start a new rails project with the latest RVM supported JRuby (9.1.13.0) and it failed here too.

**Comment by mech** [comment]
Latest JRuby 9.2 (Ruby 2.5.0) also failed for Rails 5.2 application.

**Comment by burke** [comment]
If I'm reading right, we merged a change that'll just suppress loading on JRuby. If not, anyone can feel free to open an issue to make that happen. We should just short-circuit as much as necessary to not interfere when not on MRI.

**Comment by kares** [comment]
@burke did you, could you please elaborate on that? 
since latest JRuby (9.2.6) attempted to eliminate built-in libraries and have explicit files for everything loaded ... so it should be usable with bootsnap, unless you're doing something JRuby specific ...

**Comment by burke** [comment]
Ok, sorry, I'm just trying to get caught up on a bunch of issues I've ignored for a very long time without reloading all the context up-front.

We're not doing anything JRuby-specific AFAIK. If there's anything small we can do to avoid/prevent stepping on JRuby's toes, please let me know.
