### ISSUE TITLE
Ignore permission issues in LOAD_PATH?

### ISSUE THREAD

**Issue by primerano** [Shopify/bootsnap#169]
I'm not sure if this is a bug or is working as designed.    I have a situation where RUBYLIB has been set by my admins to a path that I don't have read access to.  This isn't a problem for me because I don't use RUBYLIB for Rails my application.

But bootsnap stops the application from starting

export RUBYLIB=/root/lib  # random area i don't have permission to
rails c
ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/path.rb:28:in `stat': Permission denied @ rb_file_s_stat - /root/lib (Errno::EACCES)
from ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/path.rb:28:in `non_directory?'

Now if it points to a non-existent directory it works fine

export RUBYLIB=/foo/bar
rails c
This works

Should bootsnap treat unreachable paths the same as non-existent? 

If so path.rb could be updated in 2 places to allow my app to load without unsetting RUBYLIB.   Just add a Errno::ENOENT handler in these 2 methods.

```
      def non_directory?
        !File.stat(path).directory?
      rescue Errno::ENOENT, Errno::EACCES
        false
      end
```
```

      def latest_mtime(path, dirs)
        max = -1
        ["", *dirs].each do |dir|
          curr = begin
            File.mtime("#{path}/#{dir}").to_i
          rescue Errno::ENOENT, Errno::EACCES
            -1
          end
          max = curr if curr > max
        end
        max
      end
```

Thanks,
Tony

**Comment by burke** [comment]
(wow, sorry for the long delay here. I've ignored this project for too long)

I'm confident saying that this is Working As Intended: if a path is available to ruby in this way, it should be readable, and masking `EACCES` would probably create a number of more subtle issues than this.

I'd encourage you to just keep masking the variable, as I'm sure you're doing.

Thanks for the report, sorry for the delay.
