### ISSUE TITLE
Minimum Ruby version support?

### ISSUE THREAD

**Issue by bf4** [Shopify/bootsnap#17]
Bootsnap seems to contain >= Ruby 2.3-specific code. I haven't found where this is mentioned.  First failure on Ruby 2.2.6 is from the `<~EOF` heredoc.  I suspect subsequent failures regarding finding libyaml are similar since switching to Ruby 2.3.3 resulted in expected behavior.

**Comment by burke** [comment]
https://github.com/Shopify/bootsnap/pull/18

It's not just cosmetic; the API to marshal ruby bytecode was introduced in 2.3. We've added a minimum required version to the gemfile now though.
