### ISSUE TITLE
Atomic write cache file error.

### ISSUE THREAD

**Issue by yarhtut** [Shopify/bootsnap#171]
Can not access to `bin/rails c` on linux
ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch': Permission denied - bs_fetch:atomic_write_cache_file:open (Errno::EACCES)

We know that it is a permissions issue with our server user. As we deploy our application as a `deployer` user and are able to access the console using that role.

However when we atempt to run rails console as a `developer` role we get the following errors:

```
[WARNING] Could not load command "rails/commands/server/server_command". Error: Permission denied - bs_fetch:atomic_write_cache_file:open.
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
.../rails/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
.../rails/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
.../rails/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:84:in `block (2 levels) in lookup'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:80:in `each'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:80:in `block in lookup'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:79:in `each'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:79:in `lookup'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command.rb:70:in `find_by_namespace'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/command.rb:44:in `invoke'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
.../rails/shared/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
.../rails/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
.../rails/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
.../rails/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/app_loader.rb:59:in `block in exec_app'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/app_loader.rb:48:in `loop'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/app_loader.rb:48:in `exec_app'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/cli.rb:7:in `<top (required)>'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/exe/rails:10:in `require'
.../rails/shared/bundle/ruby/2.4.0/gems/railties-5.2.0/exe/rails:10:in `<top (required)>'
```

we are unsure what files or folders need to be created so that our `developer` user can access the console.

Are you able to provide some insight into running bootsnap with muliple users?

**Comment by johnunclesam** [comment]
+1

**Comment by austinwalter** [comment]
So I ran into this problem while on AWS Elastic Beanstalk. I don't know what setup your using, but on EBS all the directory permissions are set to 755 and files are set to 644. I used the following:

`chmod -R go+w ./tmp/cache`

Which brought my permissions in the cache directory to 777 and all files in it to 666. The console was also complaining about not being able to access the log files so I also ran:

 `chmod go+w ./log/production.log`

Since I didn't want to have to run those commands every time I wanted to access the console I add an AWS specific config file to my project that runs on deployment:

`.ebextensions/container.config`
`container_commands:
    01_set_tmp_permissions:
        command: "chmod -R go+w /var/app/ondeck/tmp/cache"
    02_set_log_permissions:
        command: "chmod go+w /var/app/ondeck/log/production.log"
`

**Comment by jasonadkison** [comment]
Thanks @austinwalter, your solution is working for me. I'd also like to know what minimum permissions are needed for what paths.

**Comment by gitjul** [comment]
Since ran into this issue now, in 2020 and this fix didn't quite work for me, I thought I'd share what did here in case someone else runs into it (hello fellow traveller 👋 ).

After re-reading the EB AWS docs about container commands, instead of `/var/app/ondeck/tmp` I changed the permissions for `/var/app/staging/tmp`:

> The specified commands run as the root user, and are processed in alphabetical order by name. Container commands are run from the staging directory, where your source code is extracted prior to being deployed to the application server. Any changes you make to your source code in the staging directory with a container command will be included when the source is deployed to its final location.

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-container-commands

So in the end my extension looks like this:

```
container_commands:
  01_set_tmp_permissions:
    command: "chmod -R go+w /var/app/staging/tmp/cache"
```

And this way I got past this particular issue on EB AWS ;) Personally I didn't need to do the same for the `production.log`.

I posted this answer on SO: https://stackoverflow.com/a/63632758/1216245
