### ISSUE TITLE
Writing a link_to method and a URL with request parameter under certain "if else" statement in Rails helper crashes with [Segmentation fault at 0x0000000000000000]

### ISSUE THREAD

**Issue by y4m4p** [Shopify/bootsnap#182]
## Stack Information
Please check the gist for more information. (Paths have been sanitized. Sorry if the path is broken)
gist: https://gist.github.com/y4m4p/26b8e213eea4a8ad1459eea8ea043595

```
(application_path)/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/compile_cache/iseq.rb:12: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

...(see gist)...

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

Abort trap: 6
```

## Environment
| program (language) | version |
|:--:|:--:|
| ruby | 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17] |
| Rails | 5.2.0 |
| Bundler | 1.16.1 |
| Mysql | 5.7.21 Homebrew |

## Overview
In any rails application, creating any helper method that satisfies all of the following conditions under `app/helpers` will crash the server, if the helper method has been loaded on startup, or called in any of the view.

- Writing a condition with `if true ... else ...` OR `if false ... else ...`
- Writing the process under the statement that will never be used. For example, if you write the `if` statement with `if true` then you must write your process under the `else` statement and vice versa.
- Write a path using the `link_to` helper and a url_helper which contains a request parameter.

For example the following method will crash the server.

```
# app/helpers/application_helper.rb

def helper_method
  if true
  else
    link_to 'somewhere', web_pages_some_view_path(foo: 'false')
  end
end
```

OR you can write it like this.

```
def helper_method
  if false
    link_to 'somewhere', web_pages_some_view_path(foo: 'true')
  else
  end
end
```

It seems that when you start up the server (which loads the helper method), and this specific method is not commented out (or deleted), it will crash the server when you try to render any views. **Even if that view does not invoke the said method.**
On the other hand, if you write the helper method after you have started up your server(like you would normally when developing the application), it is possible to explore other pages, until you try to access the said method in a view, causing it to reload the helper, thus wiping the application.

---
However This bug will not occur in the following conditions. So the following helper method will work correctly.

1. Write the true false condition statement in any variable like the following.
```
def helper_method
  condition = true (instance variable or Constants is OK too.)
  if condition
    link_to ...
  else 
    link_to ...
  end
end
```

2. Do not write the process under the statement that will never be used.
```
def helper_method
  if true
    link_to 'somewhere', web_pages_some_view_path(foo: 'true')
  else
    # link_to 'somewhere', web_pages_some_view_path(foo: 'false')  #<= comment out
  end
end
```

3. Do not give the url_helper with a request parameter.
```
def helper_method
  if true
    link_to 'somewhere', web_pages_some_view_path
  else
    link_to 'somewhere', web_pages_some_other_view_path
  end
end
```

4. Writing the method's process directly in the view template.
```
# app/view/web_pages/some_view.html.erb

<%=  if true
       link_to 'somewhere', web_pages_some_view_path(foo: 'true')
      else
        link_to 'somewhere', web_pages_some_view_path(foo: 'false')
      end %>
```

## Reproduction Application
https://github.com/y4m4p/rails_issue_33460

## Related link
https://github.com/rails/rails/issues/33460

**Comment by rafaelfranca** [comment]
I could reproduce it in a small script, without bootsnap.

```ruby
code = <<~CODE
module ApplicationHelper
  def broken_helper_in_application_helper
    if true
    else
      link_to 'somewhere', some_view_path(foo: 'false')
    end
  end
end
CODE
RubyVM::InstructionSequence.compile(code).to_binary
```

Definitely a Ruby bug.

Can you post the link of the issue here so we can follow?

**Comment by rafaelfranca** [comment]
https://bugs.ruby-lang.org/issues/14959 for reference
