### ISSUE TITLE
Sinatra has a non-conformant implementatin of caller_locations and blows up when Bootsnap uses it

### ISSUE THREAD

**Issue by julik** [Shopify/bootsnap#183]
In our applications we embed multiple Sinatra endpoints within a Rails codebase. We then make some use of the Sinatra route introspection to generate documentation etc. Sinatra includes an implementation of `caller_locations` without an argument given, defined here:

https://github.com/sinatra/sinatra/blob/4c335c2c6423ad078053babf1bdc505fe99596b6/lib/sinatra/base.rb#L1513

This implementation is common between Sinatra 2 and Sinatra 1 (we use Sinatra 1.x as embedded applications). Bootsnap always calls `caller_locations` with a Range argument. Sinatra by default assumes the use of `caller_locations` will be without arguments, which judging from this https://www.rubydoc.info/stdlib/core/2.0.0/Kernel:caller_locations since time unknown is actually calling it with `(1, nil)`. The conflicting chunk is https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb#L42 - Bootsnap overrides `require_relative` to call `caller_locations` with the `1..1` Range as argument. So Sinatra apps blow up for us since caller_locations always returns an Array:

```
rake aborted!
NoMethodError: undefined method `absolute_path' for #<Array:0x007fc5c9cabb10>
/Users/julik/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
/Users/julik/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/apiculture-0.1.0/lib/apiculture.rb:205:in `api_documentation'
```

```
julik@nanobuk frontend (rebuild-api-docs) $ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
julik@nanobuk frontend (rebuild-api-docs) $ cat Gemfile.lock | grep sinatra
    sinatra (1.4.8)
julik@nanobuk frontend (rebuild-api-docs) $ cat Gemfile.lock | grep bootsnap
    bootsnap (1.3.0)
```

I suspect this should be fixed on the Bootsnap side of things since the implementation in Sinatra is quite old and will probably not be fixed/changed to conform to the Kernel implementation for older versions. If maintainers share this suspicion I would add a very narrow rescue in the block in question _or_ add an arity check on `caller_locations` since you can detect a non-conformant implementation that way, at the cost of one extra call to `method()` and then to `#arity`. Can prepare a pull request.

**Comment by rafaelfranca** [comment]
Thank you for the issue. I think it is sinatra that have to change. Its method override is changing the method signature to no receive arguments and this is braking the method API.
