### ISSUE TITLE
10 min start and 60GB cache

### ISSUE THREAD

**Issue by x-yuri** [Shopify/bootsnap#185]
When I deploy a site, puma uses 100% CPU for about 10 min, and doesn't reply to requests. That doesn't seem to happen when I just start/restart `puma`. The cache:

```
59G     tmp/cache/bootsnap-compile-cache
231M    tmp/cache/bootsnap-load-path-cache
```

There are about 15k files in `tmp/cache/bootsnap-compile-cache/??` dirs. Unshifting every `app` subdir takes around 20 sec. I've switched to `bootsnap-1.3.1`. To no avail. Moving the file and the dir resolved the issue. Is this how it can be handled? Doesn't bootsnap clean its dirs? How is it supposed to work?

**Comment by KaraAJC** [comment]
I'm investigating this as well, and according to this previous convo in issue #153 Bootsnap doesn't have a cache cleaning/pruning mechanism. 

Unless a contributor/member has made any changes since then, Looks like cleanup will be left to the users.

**Comment by burke** [comment]
Yes, cleanup is left to users. We should document this better, but we currently don't.

The 10 minute startup is a little puzzling. We've changed some stuff relating to this since August, so I'm going to close this stale issue, but please feel free to reopen if there's still a problem.

**Comment by x-yuri** [comment]
I see nothing puzzling about 10 minute startup with 60 Gb of cache and 15k files in dirs.

**Comment by burke** [comment]
Bootsnap shouldn't be loading them if they're old cruft, but it is possible depending on the filesystem that it starts to chug on file access with 15k/0xff files per directory. You're right, it's not a major mystery.
