### ISSUE TITLE
Make libsnappy dependency optional

### ISSUE THREAD

**Issue by SamSaffron** [Shopify/bootsnap#19]
Out of the box when installing bootsnap on ubuntu it fails with 

```
etching: snappy-0.0.15.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing bootsnap:
	ERROR: Failed to build gem native extension.

    current directory: /home/sam/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/snappy-0.0.15/ext
/home/sam/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20170429-5708-1yrjbba.rb extconf.rb
checking for -lsnappy... no
./autogen.sh: 3: ./autogen.sh: aclocal: not found
./autogen.sh: 3: ./autogen.sh: aclocal: not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/sam/.rbenv/versions/2.4.1/bin/$(RUBY_BASE_NAME)
	--with-libsnappy-config
	--without-libsnappy-config
	--with-pkg-config
	--without-pkg-config
	--with-snappylib
	--without-snappylib
extconf.rb:17:in `block in <main>': `autogen.sh` failed (RuntimeError)
	from extconf.rb:14:in `chdir'
	from extconf.rb:14:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/sam/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/snappy-0.0.15/mkmf.log

extconf failed, exit code 1
```

This is since the `snappy` gem requires `libsnappy-dev` 

- Can the dependency on snappy be "optional" and then you only compress the yaml if the library is installed? 

- What kind of gains are we seeing from this yaml compression? Should this be done in the c extension to avoid the ruby gem dependency?

**Comment by burke** [comment]
I'm not strongly opposed to just removing snappy wholesale. It reduces the cache size by 30-50% in exchange for marginal time overhead on boot/update. I added it because it happened to be available in Shopify/shopify.

If we do remove it, I just don't want to require a manual process to nuke old files.

That said, I think you just need `apt-get install automake`.

**Comment by SamSaffron** [comment]
I raised it here: 

https://github.com/miyucy/snappy/issues/22

pretty sure I have automake, really for myself this is pretty trivial to sort out, its just I worry about supporting it.

**Comment by SamSaffron** [comment]
I am not seeing any performance saving by using snappy on linux

2.3~2.6 ms to load load path cache without it
2.3~2.6 ms to load load path cache with it

before snappy

```
-rw-rw-r-- 1 sam sam 249165 May  5 10:23 tmp/cache/bootsnap-load-path-cache
```

after snappy

```
-rw-rw-r-- 1 sam sam 88027 May  5 10:22 tmp/cache/bootsnap-load-path-cache
```

The space saving is significant, but performance wise it is not making a difference, I guess CPU work offsets the IO savings. 

Going to put through a PR to remove the dependency

**Comment by burke** [comment]
closed by https://github.com/Shopify/bootsnap/pull/27
