### ISSUE TITLE
Problem with Cron Job-triggered Rake Tasks

### ISSUE THREAD

**Issue by stephenamsel** [Shopify/bootsnap#208]
Running Rails 5 on Elastic Beanstalk, using Whenever and an Elastic Beanstalk Configuration file with a leader-only command to reload the Cron Tab. (I know it should be run through Lambda, but that is likely not relevant here.) The Cron jobs in turn trigger Rake tasks which must load the Rails environment to run. After adding Bootsnap, the new code was not loaded for the Cron Job, though a test-function which loaded the Rake Task from within the platform worked fine. Instead, some cached code was used so that changes to the code would not have any effect when the task was triggered by the Cron Tab.

I suspect this can be addressed either within the Gem or, for the moment, by setting some condition in boot.rb so that Bootsnap is only loaded when the server boots normally and not when the environment is loaded by a Rake task. Is there a built-in option or an easy solution of the form
```
boot.rb:
require 'bundler/setup' # Set up gems listed in the Gemfile.
if something_that_returns_true_only_if_booting_server_normally then require 'bootsnap/setup' end

```
?
I haven't checked the gem code, but I suspect this comes from the use of a relative path. Perhaps replacing it with an absolute path using Rails.root could resolve the whole matter from within the gem.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by stephenamsel** [comment]
That could be difficult: It did not reproduce in Development (only Production and only on AWS) and only appeared on an application for which I suspect my boss would not like me to post the code in any publicly visible place. I will try to put a sample application together, but without deploying sample-ode to AWS, I couldn't necessarily be sure that the error would reproduce. Will try to provide something as soon as I can, though.

**Comment by burke** [comment]
Closing stale issue; feel free to reopen if you'd like to provide more information
