### ISSUE TITLE
MacOS: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by zarapustra** [Shopify/bootsnap#211]
**ruby** 2.5.2p104 (2018-10-18 revision 65133) [x86_64-darwin17]
gem '**rails**', '~> 5.2.1'
**macos** 10.14.1
**Homebrew** 1.8.4 
gem 'bootsnap', '>= 1.1.0', require: false

	Fetching bootsnap 1.3.2
	Installing bootsnap 1.3.2 with native extensions
	Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: 	/Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/ext/bootsnap
	/Users/svezhatinka/.rbenv/versions/2.5.2/bin/ruby -r ./siteconf20181129-5180-tt2x2r.rb extconf.rb
	creating Makefile

	current directory: /Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/ext/bootsnap
	make "DESTDIR=" clean
	xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at:
	/Library/Developer/CommandLineTools/usr/bin/xcrun

	current directory: 	/Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/ext/bootsnap
	make "DESTDIR="
	xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at:
	/Library/Developer/CommandLineTools/usr/bin/xcrun

	make failed, exit code 1

	Gem files will remain installed in 	/Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2 for inspection.
	Results logged to
	/Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/bootsnap-1.3.2/gem_make.out

	An error occurred while installing bootsnap (1.3.2), and Bundler cannot continue.
	Make sure that `gem install bootsnap -v '1.3.2' --source 'https://rubygems.org/'` succeeds before bundling.

	In Gemfile:
  		bootsnap

**Comment by zarapustra** [comment]
xcode-select --install helped

**Comment by rafaelfranca** [comment]
Thanks for the issue. You were missing the command line tools to be able to compile C extensions. I'm closing since it is not an issue in the library.
