### ISSUE TITLE
Support changes in $LOADED_FEATURES

### ISSUE THREAD

**Issue by fxn** [Shopify/bootsnap#224]
Right now, the decorated `require` trusts its cache:

```ruby
return false if Bootsnap::LoadPathCache.loaded_features_index.key?(path)
```

So it does not preserve `require` semantics:

```ruby
require "foo" # => true
$LOADED_FEATURES.pop
require "foo" # => false, should be true
```

I've seen some comments in the code base where it is clear this is a known trade-off rather than an overlook.

I am raising this issue because Zeitwerk depends on `require` semantics in the sense that `require` checks whatever `$LOADED_FEATURES` has at the moment. It needs that behavior because that is the trick it uses to have new autoloads load the same file again on reload, Zeitwerk [removes the files from `$LOADED_FEATURES`](https://github.com/fxn/zeitwerk/blob/master/lib/zeitwerk/loader.rb#L198).

I don't know `bootsnap` enough to think about how we could make both things play well together, but something that comes to mind is that if the cache has the file, then just call `require` with the corresponding absolute path. That is a trade-off, there is an extra `$LOADED_FEATURES` lookup, but it is complaint.

What do you think?

**Comment by fxn** [comment]
Another idea that could be perhaps related, is that perhaps `bootsnap` could ignore calls with absolute paths. Zeitwerk internally works only with absolute paths.

Not exactly a proposal, you know better the principles behind `bootsnap`, just an idea that came to mind while looking into this.

**Comment by fxn** [comment]
Well, to be exact, Zeitwerk sets autoloads using only absolute paths, and preloads/eager loads using absolute paths. Projects managed by Zeitwerk do not even need to be in `$LOAD_PATH`, it just works if they are not by design.

But if `require` gets a relative path it [still tries to play well with it](https://github.com/fxn/zeitwerk/blob/e0b8ca3d94614f901b81ecf9fc5a58675e054ba0/lib/zeitwerk/kernel.rb#L23-L29) in case client code of gems using Zeitwerk issues some.

That is undocumented, it is an attempt to do as much as possible to work seamlessly.

**Comment by rafaelfranca** [comment]
cc @burke

**Comment by burke** [comment]
Hm, this is likely going to be tricky.

First point, we do some rather gross monkeypatching of the ActiveSupport autoloader (https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/load_path_cache/core_ext/active_support.rb). I'm not sure how much of this becomes irrelevant with, or conflicts with, Zeitwerk.

I'm not, in principle, opposed to making some minor performance compromises here to accommodate Zeitwerk.

It's really too bad that `$LOADED_FEATURES` is modified from C-land, so we can't simply hook all the cases where it's mutated like we're able to with `$LOAD_PATH`; that said, we should be able to hook whichever method Zeitwerk is using to mutate it, and probably respond accordingly to that manipulation.

**Comment by fxn** [comment]
Hey @burke!

The integration is still WIP, but it could be the case that the Active Support monkey patches in `bootsnap` do not interfere. The way Zeitwerk is being integrated is basically by calling `take_over` from [this module](https://github.com/rails/rails/blob/fxn/zeitwerk/activesupport/lib/active_support/dependencies/zeitwerk_integration.rb) at some point in the initialization process. (Warning: I am force pushing to that branch.)

As you see, it is a quite lightweight decoration to preserve a subset of the interface that I have considered worth maintaining by now. The key observation that simplifies this integration is that `Kernel#autoload` is called before `const_missing`. Therefore, for a correct project structure, the autoloading code of AS::Dependencies won't ever run.

It could be the case that I unhook also AS::Dependeces in `take_over`, just to play safe. And it could be the case that instead of `bootsnap/setup` we generate a setup that disables `bootsnap`'s monkey patch (from memory I believe that happens if you disable `auto_load_paths`). All is speculative right now.

But `bootsnap` worked as is in a simple application, the only think that didn't work was reloading, for the reasons we are studying here. At least by now, maybe other things may be waiting to be discovered, but by now that is what I've seen.

Zeitwerk only calls `$LOADED_FEATURES.delete` on reload. A reload is triggered by Rails when code changes, or when you call `reload!` in the console, for example. You know. Anything that invokes `AS::Dependencies.clear`. Maybe that helps leaning on a particular approach?

**Comment by kaspth** [comment]
Maybe Zeitwerk could broadcast when reloading happens and it thus mutates $LOADED_FEATURES or similar like that? Instead of preying on the mutation.

**Comment by fxn** [comment]
Well, Zeitwerk itself is agnostic in that sense, it just offers `reload` in case client code is a serivce that monitors the file system and wants to refresh the code.

But the Rails integration could call once a method that invalidates `bootsnap` cache, for example:

```ruby
def clear
  Dependencies.unload_interlock do
    Rails.autoloader.reload
    Bootsnap.rescan
  end
end
```

That is what I meant above by saying

> Similarly, that integration point could tell `bootsnap` to invalidate its cache.

I have to say that as far as `require` is concerned `bootsnap` is not necessary for projects managed by Zeitwerk, because the library directly issues `require` calls with absolute paths scanning once. But if Rails ships both of them, at least they should be able to coexist.

**Comment by fxn** [comment]
Regarding the last paragraph, if `bootsnap` had a way to say "do not cache anywthing volatile, only stable", that could also be a possibility for Rails integration maybe.

**Comment by fxn** [comment]
Let me summarize the different options so far and the what I believe are the cons of each one:

1. Provide API or a Rails reloader to scan again when the file system has changed: Costly and with little benefit. Zeitwerk is carefully lazy scanning the app tree precisely thinking about the cost of a tree traversal in Shopify's code base (discussed with @rafaelfranca). A rescan from `bootsnap` would defeat that optimization. Additionally, it would do so with little benefit, since code managed by Zeitwerk does not issue `require` calls with relative paths and `bootsnap` cache for relative paths won't be leveraged.

2. Let `require` call the parent implementation with the cached absolute path instead of returning a hard-coded `false` for loaded files: the cache may be stale.

3. Provide API to ignore so-called volatile paths: Since `bootsnap` would only scan a subset of `$LOAD_PATH`, it could resolve to a wrong filename if the relative path should resolve to something outside the stable paths due to a (maybe deliberate) name coincidence.

4. Ignore `require` calls with absolute paths totally, do not cache, always pass them up: The user may exceptionally call `require` or `require_dependency` for whatever reason with a relative path, and we are at square one.

**Comment by burke** [comment]
1.4.0.pre2 is pushed to rubygems, should work for you I *think*.

**Comment by fxn** [comment]
I believe this is working now, let's close.
