### ISSUE TITLE
incompatible library  with Ruby 2.6.1

### ISSUE THREAD

**Issue by joshm1204** [Shopify/bootsnap#228]
/Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require': incompatible library version - /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/bootsnap.bundle (LoadError)
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/compile_cache/iseq.rb:1:in `<top (required)>'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/compile_cache.rb:5:in `setup'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap.rb:30:in `setup'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/setup.rb:33:in `<top (required)>'
	from /Users/myuser/myapp/config/boot.rb:4:in `require'
	from /Users/myuser/myapp/config/boot.rb:4:in `<top (required)>'
	from /Users/myuser/myapp/config/application.rb:1:in `require_relative'
	from /Users/myuser/myapp/config/application.rb:1:in `<top (required)>'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/myuser/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by rafaelfranca** [comment]
Make sure your bootsnap gem was installed and compiled with the right ruby version. `gem uninstall bootsnap` should fix this issue.

**Comment by joshm1204** [comment]
What is the "right" ruby version? thanks

**Comment by rafaelfranca** [comment]
the same you are planning to use. If you want to use 2.6.1 make sure bootsnap was installed using that version. If you want to use 2.5.1 make sure it was installed using that version.

**Comment by burke** [comment]
Looks like this was solved, please reopen if not.
