### ISSUE TITLE
Minimum version of active support?

### ISSUE THREAD

**Issue by bibendi** [Shopify/bootsnap#23]
What is the minimum required version of active support?

**Comment by jules2689** [comment]
We haven't really tested that. Here is an overview of what we override.

| method | sha introduced | when? |
| --- | --- | --- |
| `autoload_paths=` .   | 4a0a640d33e1c729d38c6091bb1394fbda059b5c | 7 years ago |
| `search_for_file` | da91450e687fe9faa7b0575062c2b2aacc261f68 | 11 years ago |
| `autoloadable_module?` | 053d057a88ac7c4a713666a58306861a2b1bd78c | 11 years ago |
| `remove_constant` | 053d057a88ac7c4a713666a58306861a2b1bd78c | 11 years ago |
| `load_missing_constant` | da91450e687fe9faa7b0575062c2b2aacc261f68 | 11 years ago |
| `depend_on` | bd323b3c99437cf1a50d7b4c23a64f296859c56a | 13 years ago |

As long as those methods are there, I'd assume it would work. `4a0a640d33e1c729d38c6091bb1394fbda059b5c` is the latest at 7 years ago, this is Rails 3.0.0. So I would assume that `bootsnap` *should* work for `>= 3.0.0.beta3`.

If you find an actual minimum, we'd be happy to mention that.

**Comment by bibendi** [comment]
According to our tests on Rails 3.2 did not work.
And besides this Rails 3.2 require Ruby version less then 2.3 ;)
So it seems to me that the minimum version of Rails is 4.0

**Comment by TheRusskiy** [comment]
In ActiveSupport 3.2 api for `depend_on` is different
https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/dependencies.rb#L311
vs
https://github.com/rails/rails/blob/4-0-stable/activesupport/lib/active_support/dependencies.rb#L287

**Comment by TheRusskiy** [comment]
here's a pull request if you deem necessary to fix that https://github.com/Shopify/bootsnap/pull/36
