### ISSUE TITLE
Unnecessary stack traces generated for flow-control exceptions

### ISSUE THREAD

**Issue by headius** [Shopify/bootsnap#231]
There are two flow-control exceptions I noticed in bootsnap: https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/load_path_cache.rb#L3-L4

These appear to only be used to unroll the stack from two places:

https://github.com/Shopify/bootsnap/blob/22f40edf6d5b231bcdfb22a2b928d49f07d84da6/lib/bootsnap/load_path_cache/cache.rb#L81

and

https://github.com/Shopify/bootsnap/blob/22f40edf6d5b231bcdfb22a2b928d49f07d84da6/lib/bootsnap/load_path_cache/cache.rb#L59

In both cases, the stack trace generated for the exception does not appear to ever be captured. You could reduce the overhead of these flow-control exceptions one of three ways:

1. Use a single cached instance of the exception
2. Use catch/throw instead of raise/rescue.
3. Use the three-argument form of `raise` that takes a backtrace, e.g. `raise ReturnFalse, "", []`

On the JVM, generating stack traces for exceptions like these costs at least a few milliseconds.

**Comment by burke** [comment]
> Use the three-argument form of `raise` that takes a backtrace, e.g. `raise ReturnFalse, "", []`

🤯 whoah, TIL. Thanks, I'll do this right away.
