### ISSUE TITLE
Can't load ActiveRecord on boot (Ruby 2.5.1, Rails 5.2.2)

### ISSUE THREAD

**Issue by tadiou** [Shopify/bootsnap#235]
Similar to #176, except that instead of failing on `ActiveSupport` it's failing on `ActiveRecord`.

Attempted to try to manually require both `active_support/dependencies` and `active_record` in boot (which normally looks like this, nothing out of the ordinary)

```ruby
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.
```

Error always ends up being some variation of this:
```
Failure/Error: require File.expand_path("../config/environment", __dir__)

LoadError:
  cannot load such file -- active_record
# ./config/application.rb:10:in `<top (required)>'
```
`application.rb` looks like the following
```ruby
require_relative "boot"

require "rails/all"
require "./lib/content"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

# Load Secrets
require "./config/initializers/_settings"
```

Amusingly, when I upgrade to Ruby 2.5.3, this doesn't become an issue anymore.

**Comment by rafaelfranca** [comment]
It is probably because you clean the cache when you upgrade ruby. Did you try to remove the boosnap cache to see if it fixes the issue? The cache is inside `tmp/cache`

**Comment by tadiou** [comment]
Thanks!
