### ISSUE TITLE
Do not observe changes in frozen arrays

### ISSUE THREAD

**Issue by fxn** [Shopify/bootsnap#236]
The change observer tries to set an ivar on the given array object, and decorate it:

```ruby
def self.register(observer, arr)
  arr.instance_variable_set(:@lpc_observer, observer)
  arr.extend(ArrayMixin)
end
```

The purpose seems to be to wrap the API that modifies the object to monitor modifications. That is not possible if the array is frozen, but also, not needed because it won't change.

What do you think about bypassing registration in that case?

References https://github.com/rails/rails/issues/35278.

**Comment by burke** [comment]
This seems like a completely reasonable idea to me. I'll try to get around to it this week.

**Comment by burke** [comment]
Fixed in https://github.com/Shopify/bootsnap/commit/0a6d32d45eb8856515a706c543f30e27bae4f2fc

**Comment by fxn** [comment]
❤️
