### ISSUE TITLE
The PGconn, PGresult, and PGError constants are deprecated

### ISSUE THREAD

**Issue by stefanahman** [Shopify/bootsnap#238]
Hello,

I'm getting the following warning:

```
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /home/user/app/shared/bundle/ruby/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
```

**Comment by burke** [comment]
It's unfortunate that bootsnap can sometimes appear to be the source of unrelated errors by nature of how it inserts itself into the system, but that is what's happening here. I'd look into what code is actually calling `PGresult`, etc., and update that code (probably a gem). Bootsnap doesn't use postgres.

**Comment by stefanahman** [comment]
Ah, that makes total sense. Thank you for the reply!
