### ISSUE TITLE
problems with bootsnap (on ruby/rails)

### ISSUE THREAD

**Issue by MikkelDK** [Shopify/bootsnap#265]
Hello,

I'm using Ubuntu 19.04
I have some weird problems with "Bootsnap" version 1.4.4

Error:
`/var/lib/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- composite_io (LoadError)`

This happens only, if I try run command of: ``rails s``

**Comment by burke** [comment]
It's unlikely to be a problem with bootsnap, it's just that bootsnap shows up in the trace because it monkeypatches require. Almost certainly this is just a failure to require composite_io in the same way as it would if bootsnap wasn't enabled.

Feel free to reopen if I'm wrong about that.
