### ISSUE TITLE
Not able to run the ruby on rails gitlab code into my local

### ISSUE THREAD

**Issue by nishantsverma** [Shopify/bootsnap#266]
I have taken my code from gitlab. Now I have setup the code into my local. While running the rails server, I see following error:

Traceback (most recent call last):
        4: from bin/rails:3:in `<main>'
        3: from bin/rails:3:in `load'
        2: from C:/Users/nverma1/assistance-development/bin/spring:8:in `<top (required)>'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)

**Comment by sergey-alekseev** [comment]
@nishantsverma how is this related to bootsnap?

**Comment by rafaelfranca** [comment]
This doesn't seems to be related to bootsnap. Let us know if you have more information that can point to a problem on this gem. Thank you.
