### ISSUE TITLE
rake aborted! stack level too deep when db:migrate

### ISSUE THREAD

**Issue by cactus171** [Shopify/bootsnap#272]
my project has many large migration files.
stack level too deep error occurs when executed 'RAILS_ENV=test bundle exec rake app:setup'
but not repro comment out "require 'bootsnap'" and Bootsnap.setup in boot.rb

```
rake aborted!
SystemStackError: stack level too deep
```

using
ruby 2.6.4
rails 6.0.0
bootsnap 1.4.5

Thank you

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by cactus171** [comment]
Maybe it was fixed by ruby 2.7

Thank you
