### ISSUE TITLE
How does `Kernel.require` in bootsnap work with Rails 6?

### ISSUE THREAD

**Issue by schneems** [Shopify/bootsnap#275]
Not an issue in bootsnap exactly, but I [came across an issue](https://github.com/rails/rails/issues/37308) while using nearly identical code to bootsnap's `core_ext/kernel_require.rb` inside of a project with Rails 6. 

Did you all hit this and mitigate it somehow, or is this not an issue with bootsnap somehow, or is bootsnap silently failing and not being called for some requires?

Here's my Rails issue https://github.com/rails/rails/issues/37308 with reproduction script.

Thanks a ton for your work on bootsnap!

**Comment by rafaelfranca** [comment]
We avoid that by monkey patch `require` before Zeitwerk do it and because of that we avoid that problem. It is just a consequence of they way we inject bootsnao in applications.

**Comment by schneems** [comment]
Thanks, that makes sense.
