### ISSUE TITLE
development_mode

### ISSUE THREAD

**Issue by suan** [Shopify/bootsnap#28]
What does `development_mode` actually do?

**Comment by SamSaffron** [comment]
from reading the code it makes the cache do more work and assumes it is always stale. I think you would use it if you were developing "bootsnap" 

@burke does this even need to be so prominent in the documentation? I would only add it in a section for "developing bootsnap" or something like that.

**Comment by burke** [comment]
It's intended to be used in situations where the contents of application source directories may change. When development_mode is false, for example, we scan the contents of lib/ once at boot and assume it never changes. This would cause ugly errors in long-running servers where the user adds a file in lib/ and expects it to be autoloaded or things like this.
