### ISSUE TITLE
The 'disable_trace' method is not allowed with this Ruby version. current: 2.6.3, allowed version: < 2.5.0

### ISSUE THREAD

**Issue by DmzTheo** [Shopify/bootsnap#281]
I have this error when starting rails server. Do you know if bootsnap still working ?
Thanks.
Théo

**Comment by rafaelfranca** [comment]
Yes. Bootsnap is still working. If you are setting `disable_trace` to true you need to remove it. Also make sure you are using the latest version of bootsnap.
