### ISSUE TITLE
Can't load kernel_require.rb:32

### ISSUE THREAD

**Issue by mkbctrl** [Shopify/bootsnap#286]
Hey, when I am trying to run `rails server` I am getting the process aborted due to the following problem:

```
.rvm/gems/ruby-2.5.3@project-name/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- dry/validation/schema/form (LoadError)
```

are you aware how can I fix it? Google does not provide and useful ideas.

I am running on Mac OS Catalina 10.15.1 - I had some kernel related issue with the curb gem, where I had to upgrade it from 0.9.3 to 0.9.10. Maybe this case is somehow related. Since I am not a backend developer, I can only guess what’s going on here.

**Comment by burke** [comment]
sorry for the late reply. most likely it has nothing to do with bootsnap; it's just that bootsnap inserts itself into `require`. not sure what the actual problem would be though.
