### ISSUE TITLE
Tag new release (v1.4.6 or 1.5.0)

### ISSUE THREAD

**Issue by WarheadsSE** [Shopify/bootsnap#293]
After the merge of https://github.com/Shopify/bootsnap/pull/283 on month ago, new release has not been tagged.

This change is fairly significant for users of portable or containerized environments, as was found in the [testing of enablement within GitLab's own containers](https://gitlab.com/gitlab-org/charts/gitlab/-/merge_requests/1157#note_283055268).

Please tag a new release, so that we can properly bump `Gemfile` & `Gemfile.lock`s for maintainable releases :bowing_man: 

cc @stanhu

**Comment by burke** [comment]
Done, sorry for the delay.

**Comment by WarheadsSE** [comment]
Thank you very much @burke :bowing_man:
