### ISSUE TITLE
rail server not starting

### ISSUE THREAD

**Issue by rajeshpatel52** [Shopify/bootsnap#300]
rajesh@rajesh-HP-Compaq-8200-Elite-SFF-PC:~/blog$ rails server
Traceback (most recent call last):
	4: from bin/rails:3:in `<main>'
	3: from bin/rails:3:in `require_relative'
	2: from /home/rajesh/blog/config/boot.rb:3:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
****"I am new to this please can anybody help to solve this error"

**Comment by rafaelfranca** [comment]
Thank you for the issue. How did you generated this application? What is your environment? Ruby version? Rails version? How did you installed Ruby? Are you able to execute this script:

Create a file called `test_bundler.rb` with:

```ruby
require "bundler/setup"
```

And then call:

`ruby test_bundler.rb`

Does it work?

**Comment by rajeshpatel52** [comment]
thank you imanaged to find solution

**Comment by rafaelfranca** [comment]
Thank you. I'm closing this issue but could you share your solution? Other people may benefit from it.
