### ISSUE TITLE
Redefinition of YAML.load_file Doesn't Support New Fallback Option in Recent Ruby Versions

### ISSUE THREAD

**Issue by chadrschroeder** [Shopify/bootsnap#303]
Recent versions of `YAML` introduced a `fallback` option.  First it was [a normal param here](https://docs.ruby-lang.org/en/2.3.0/Psych.html#method-c-load_file) and later it became a [named param](https://docs.ruby-lang.org/en/2.5.0/Psych.html#method-c-load_file).  This option decides what is returned when the file is empty:

```ruby
# Testing in an app without bootsnap, Ruby version 2.6.6
YAML.load_file('empty_file.yml')
 => false

YAML.load_file('empty_file.yml', fallback: {})
 => {}
```

The [bootsnap redefinition of `load_file`](https://github.com/Shopify/bootsnap/blob/v1.4.6/lib/bootsnap/compile_cache/yaml.rb#L49) doesn't include this `fallback` param.  So if you are running an app that uses `bootsnap` and you try to use it an exception is raised:

```ruby
# Testing in an app that uses bootsnap version 1.4.6, Ruby version 2.6.6
YAML.load_file('empty_file.yml')
 => false

YAML.load_file('empty_file.yml', fallback: {})
ArgumentError (wrong number of arguments (given 2, expected 1))
```

We are able to work around this by not using the `fallback` param like:

```ruby
YAML.load_file('empty_file.yml') || {}
```

But I just wanted to document the problem in case others run into it and so that hopefully a fix can come out at some point.

**Comment by burke** [comment]
This probably wouldn't be a difficult contribution if any curious reader feels like tackling this.

**Comment by casperisfine** [comment]
This was fixed in https://github.com/Shopify/bootsnap/pull/320
