### ISSUE TITLE
Rubygems's require frustrates bootsnap load path cache optimization

### ISSUE THREAD

**Issue by vihai** [Shopify/bootsnap#307]
Hello,

I was investigating why a non-rails application did not get any speed improvements.
I straced this simple code:

```ruby
require 'bootsnap'

Bootsnap.setup(
  cache_dir:            '.',
  development_mode:     false,
  load_path_cache:      true,
  autoload_paths_cache: false,
  disable_trace:        true,
  compile_cache_iseq:   false,
  compile_cache_yaml:   false,
)

puts "-------------------------------------------------------------------------------"
require 'optparse'
puts "-------------------------------------------------------------------------------"
```

And I noticed it triggered the usual avalanche of lstat+stat searching into every `$LOAD_PATH` component.

I noticed that rubygem's somewhere replaces Kernel#require with its own from `/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:34` that apparently frustrates bootsnap's optimizations.

I looked into your code and I saw you monkeypatch `module Kernel` with your own version of `require`, however this very unexpected behavior happens:

```ruby
puts "1 Kernel#require=#{Kernel.method(:require)}"

module Kernel
  alias_method(:require_without_bootsnap, :require)
end

puts "2 Kernel#require=#{Kernel.method(:require)}"
puts "2 Kernel#require_without_bootsnap=#{Kernel.method(:require_without_bootsnap)}"
puts "2 Kernel#gem_original_require=#{Kernel.method(:gem_original_require)}"
```
Has this output:

```
1 Kernel#require=#<Method: Kernel.require(_)>
2 Kernel#require=#<Method: Kernel.require(_)>
2 Kernel#require_without_bootsnap=#<Method: Kernel.require_without_bootsnap(require)(path) /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:34>
2 Kernel#gem_original_require=#<Method: Kernel.gem_original_require(require)(_)>
```

So it appears that aliasing `Kernel#require` does not alias the true original `require` but the patched version from rubygems.

In facts I I was able to get the optimization by replacing `require_without_bootsnap(resolved || path)` with `gem_original_require(resolved || path)`.

My environment:
Ubuntu 20.04
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
rubygems 3.1.2

Also tested with ruby 2.5.5p157, rubygems 2.7.6.2

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by casperisfine** [comment]
Closing as not reproducible.
