### ISSUE TITLE
Missing 1.5.0 Java Release

### ISSUE THREAD

**Issue by drcapulet** [Shopify/bootsnap#330]
Hey y'all - the 1.5.0 java release seems to be missing from RubyGems, mind publishing it please?

**Comment by casperisfine** [comment]
@rafaelfranca I see you published version 1.4.9 using Shipit and it has the java version, however the 1.5.0 and 1.5.1 I published using shipit as well don't. 

Did I forget something?

**Comment by rafaelfranca** [comment]
We need to do the release manually for those version given we don't have JRuby on shipit. I can do it if you don't want to setup your machine with JRuby.

**Comment by casperisfine** [comment]
> I can do it if you don't want to setup your machine with JRuby.

That would indeed save me a lot of troubles. Thank you.

**Comment by rafaelfranca** [comment]
Both versions were published. Thank you for reporting.

**Comment by nerdrew** [comment]
Are 1.6.0 and 1.7.0 also missing their java versions?

**Comment by casperisfine** [comment]
Ah yeah, I always forgot. I'll have to look into it, not sure how to publish them

What are they for anyway? I don't quite understand.

**Comment by casperisfine** [comment]
@nerdrew curious, can you install https://rubygems.org/gems/dedup on JRuby? If so I think I can use the same trick for bootsnap to remove the need for Java platform gems.

**Comment by casperisfine** [comment]
I release a 1.7.1.pre1 which I believe should work for all platforms: https://rubygems.org/gems/bootsnap

I'd appreciate if someone familiar with jruby & such could confirm it works as intended.

**Comment by reidmorrison** [comment]
Thank you @casperisfine , `1.7.1.pre1` works great with JRuby and Ruby 3.0

**Comment by casperisfine** [comment]
Great. Regular 1.7.1 is out using the same method.
