### ISSUE TITLE
Support for Rails 6.1

### ISSUE THREAD

**Issue by kapso** [Shopify/bootsnap#338]
I see this error

`bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant': uninitialized constant ActiveModel::Error (NameError)`

**Comment by byroot** [comment]
Could you provide a larger backtrace please?

I suppose this comes from the classic autoloader integration. We should probably remove it now that the classic autoloader is deprecated, as Zeitwerk only require absolute paths.

**Comment by byroot** [comment]
I forgot: in the meantime setting `autoload_paths_cache: false` should solve your issue.

**Comment by kapso** [comment]
Actually, nevermind -- seems to work alright. Closing this issue.

**Comment by kofiasare** [comment]
> Actually, nevermind -- seems to work alright. Closing this issue.

@kapso, how did you resolve this? 
As I face the same challenge 
``/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant': uninitialized constant Regex (NameError)
Did you mean?  Regexp``
