### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by hmcfletch** [Shopify/bootsnap#34]
Love the gem. Saw the 50% speed up on my own machine, just like you mentioned. I have a few questions:

1. Since I am seeing a number of issues regarding problems with linux machines, would it make sense add the gem only in the `development` group?
2. How Bootsnap prevented from running in production?
3. The `BootLib::Require` pro tip does not work for me. Throws an error, `uninitialized constant BootLib`
4. Does Bootsnap have away to disable it for devs not running osx?
5. Seems like this would work great for speeding up tests as well. But without the linux support, wouldn't work with CI setups, so we'd need to be able to turn Bootsnap off in that case.
6. We do a lot of git branch switching, I am assuming that this invalidates the cache.

I'm running Rails 4.2.7.1 and added the Bootsnap code to `config/boot.rb`.

Figured if I had these questions, someone else might as well.

**Comment by hmcfletch** [comment]
I'd be happy to do a PR to add the answers to these questions if that helps.

**Comment by burke** [comment]
> Since I am seeing a number of issues regarding problems with linux machines, would it make sense add the gem only in the development group?

It's completely fine to include on linux, but I would recommend setting the compile_cache features to `RUBY_PLATFORM =~ /darwin/` instead of `true`.

> How Bootsnap prevented from running in production?

See 1

> `BootLib::Require`

There's a link in that line too, you have to add the code from the wiki in order for that to work. It's just a little widget extracted from our codebase.

> Does Bootsnap have away to disable it for devs not running osx?

Yeah, you can just use that `RUBY_PLATFORM =~ /darwin/` trick.

> We do a lot of git branch switching, I am assuming that this invalidates the cache.

Hm, it shouldn't, unless your branches are *massively* divergent.

**Comment by burke** [comment]
Probably we should document the suggestion about using `RUBY_PLATFORM =~ /darwin/` in place of a boolean for the compile cache features.

**Comment by davidpaulhunt** [comment]
@burke re: the code for the widget `BootLib::Require` - does the code have to be in the `boot.rb` file - i/e the same file as you're calling the module or can you split the actual module code out into a separate `boot_lib.rb` file?

I'm asking while assuming the answer is no given the Rails initialization order; would love to be wrong though!

**Comment by burke** [comment]
You can put it somewhere separate, yeah, you'd just want to `require_relative` it to prevent another `LOAD_PATH` scan.

**Comment by davidpaulhunt** [comment]
Oh nice, that's good to know. Thanks!

**Comment by hmcfletch** [comment]
I put it in `lib/boot_lib_require.rb` and did:
```ruby
require File.expand_path('../../lib/boot_lib_require.rb', __FILE__)
BootLib::Require.from_gem('bootsnap', 'bootsnap')
```

**Comment by hmcfletch** [comment]
@burke I'm having issues running `bundle exec rake test` and am getting:
```ruby
Bootsnap::LoadPathCache::PathScanner::RelativePathNotSupported: Bootsnap::LoadPathCache::PathScanner::RelativePathNotSupported
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/path_scanner.rb:16:in `call'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/path.rb:60:in `scan!'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/path.rb:52:in `entries_and_dirs'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/cache.rb:137:in `block (2 levels) in unshift_paths_locked'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/cache.rb:134:in `each'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/cache.rb:134:in `block in unshift_paths_locked'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/store.rb:43:in `transaction'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/cache.rb:133:in `unshift_paths_locked'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/cache.rb:90:in `block in unshift_paths'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/cache.rb:90:in `synchronize'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/cache.rb:90:in `unshift_paths'
.../gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/change_observer.rb:27:in `block in register'
.../gems/railties-4.2.7.1/lib/rails/test_unit/sub_test_task.rb:112:in `block in define'
.../gems/railties-4.2.7.1/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
.../gems/railties-4.2.7.1/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
.../bin/ruby_executable_hooks:15:in `eval'
.../bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test:run
(See full trace by running task with --trace)
```

I don't expect you to know the answer for my particular set up, but do you have a tip on how to hunt down the relative path that is causing the issue? I'm not seeing any of my code, so I'm a bit lost.

**Comment by burke** [comment]
Yeah, the problem seems to be that your `$LOAD_PATH` already contains a relative path (i.e. anything that doesn't start with `'/'`) when you're loading bootsnap. You could just stick a `puts $:` before you require bootsnap.

Here's some discussion on why we don't support relative paths: https://github.com/Shopify/bootsnap/pull/26

**Comment by Xymist** [comment]
I've been seeing the same issue - Rspec and Puma are happy, `rake test` is not. Strangely if I put `puts $LOAD_PATH` or `puts $:` before the require, the list returned doesn't include any relative paths. However, if I patch `lib/bootsnap/load_path_cache/path_scanner.rb`:

```
raise RelativePathNotSupported, '$LOAD_PATH contains relative path: ' + path unless path.start_with?(SLASH)
```

The path it thinks is a problem is `test`. Just that, nothing else. Trying to work out where that's coming from, since it (apparently) isn't included in the $LOAD_PATH beforehand.

**Comment by nateberkopec** [comment]
[Bingo](https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/testing.rake#L9).

**Comment by nateberkopec** [comment]
Weirdly, turning load path caching off does not stop the error. Is there any workaround for this? Otherwise it looks like this gem can't be used with Rails and testunit/minitest in a test environment.

**Comment by nateberkopec** [comment]
For people who want a solution Right Now for using bootsnap with Rails and Minitest, [overriding all the tasks seems to work](https://github.com/codetriage/codetriage/pull/551/commits/b7a37b8e46f821cbba85d78545aeddeed5fbcb55#diff-52c976fc38ed2b4e3b1192f8a8e24cffR31).

**Comment by burke** [comment]
I just released 0.3.1, which supports relative paths.

**Comment by hmcfletch** [comment]
Will we need to clear the current cache, or will it work with just updating the gem? Not a big thing, just curious.

**Comment by burke** [comment]
It should just work.

**Comment by ixti** [comment]
Pretty offtopic, but I saw you [mentioned](https://github.com/Shopify/bootsnap/issues/34#issuecomment-302780818):

> Probably we should document the suggestion about using `RUBY_PLATFORM =~ /darwin/` in place of a boolean for the compile cache features.

Does it means "it was not tested on non-OSX" or "it's guaranteed to cause unexpected behavior on non-OSX"? What about Linux?

**Comment by lime** [comment]
> Does it means "it was not tested on non-OSX" or "it's guaranteed to cause unexpected behavior on non-OSX"? What about Linux?

Bootsnap previously used a caching mechanism that only worked reliably on OSX. Since https://github.com/Shopify/bootsnap/pull/43 that's no longer the case, so the comments are outdated. :)

**Comment by ixti** [comment]
@lime Huge! Thank you! Makes sense!

**Comment by burke** [comment]
Lots has changed; please reopen if these questions still need answering.
