### ISSUE TITLE
Bootsnap 1.7.0 gives sporadic "Unable to autoload constant" errors

### ISSUE THREAD

**Issue by sco11morgan** [Shopify/bootsnap#347]
When I upgraded from 1.6.0 to 1.7.0 I started getting flakey "Unable to autoload constant" errors on CI.  I reverted back to 1.6.0 and everything is good.

Not sure what other info would be useful to track down the problem.

**Comment by casperisfine** [comment]
> Not sure what other info would be useful to track down the problem.

Hum, Ruby version, Rails version, which autoloader you use, and any backtrace / full error message would help.

**Comment by casperisfine** [comment]
Oh let me bet, you are on Ruby 2.5.x with Zeitwerk?

**Comment by sco11morgan** [comment]
Ruby 2.6.4, Rails 5.2.4.4.  No zeitwerk.  The constant it failed to load was one of our application classes.

**Comment by casperisfine** [comment]
Hum, then I really don't see what in the diff could cause any of that: https://github.com/Shopify/bootsnap/compare/v1.6.0...v1.7.0

There wasn't any real change to ISeq caching in that range. You should try to figure out what's the original exception that is making the autoload fail.

**Comment by sco11morgan** [comment]
OK, so it looks like there are a few factors at play, but the villain is the Rails autoloader which apparently [is not thread-safe](https://github.com/rails/rails/issues/25807#issuecomment-532438725)

The area of our code that was causing the autoload exception uses the parallel gem to run some parts multithreaded.  And even though we wrap each thread with `Rails.application.executor.wrap` there is still a problem with autoload.

The other factors are that we put the bootsnap precompile (`bundle exec bootsnap precompile --gemfile`) in the Docker image that runs on CI as well as updated to 1.7.0.  This may somehow exacerbate the autoload threading issue.

I've enabled Rails `eager_load` for CI (which is better since that is what is used in production) and the problem went away.
