### ISSUE TITLE
regular expression has redundant nested repeat operator '*'

### ISSUE THREAD

**Issue by dima4p** [Shopify/bootsnap#354]
/usr/local/rvm/gems/ruby-2.7.1@logan/gems/bootsnap-1.7.3/lib/bootsnap/compile_cache/iseq.rb:19: warning: regular expression has redundant nested repeat operator '*'

**Comment by casperisfine** [comment]
That's not bootsnap, that's your own code. It's reported as coming from bootsnap because it's the one loading your code.

Disable bootsnap entirely and you'll see the same warning.

**Comment by dima4p** [comment]
> That's not bootsnap, that's your own code. It's reported as coming from bootsnap because it's the one loading your code.
> 
> Disable bootsnap entirely and you'll see the same warning.

OK, thanks, sorry.
