### ISSUE TITLE
Precompilation & Load Path Cache

### ISSUE THREAD

**Issue by metaskills** [Shopify/bootsnap#355]
I am working on optimizing some cold starts for Rails in AWS Lambda (https://lamby.custominktech.com) and wonder if you could describe why the [precompilation command](https://github.com/Shopify/bootsnap#precompilation) does not also add the `load-path-cache`. My goal is to have this in place for the Docker image deployed to Lambda so Rails boots faster. 

I've come up with a workaround to do just that. But hoping y'all can add some context as to how the load path cache is supposed to work.

**Comment by casperisfine** [comment]
I think I didn't add it because that cache is dependent on the `$LOAD_PATH`, and that it's hard to predict an app `$LOAD_PATH` without booting it.

But if you have some ideas or rough patches, feel free to submit them.

**Comment by metaskills** [comment]
Another thing to note is that Lambda is a read-only file system. My method to build the `load-path-cache` is to simply add something like this to the Dockerfile.

```dockerfile
RUN bundle exec bootsnap precompile --gemfile app/ lib/ && \
    LAMBY_BUILD=1 bundle exec ruby app.rb
```

Where `app.rb` here does the typical requires for Rails boot, application, environment and defines the Lambda handler. This does generate a good looking `load-path-cache` within the Lambda Container. Still testing benchmarks. 

However, one big hurdle I had to overcomes is that this file is opened and re-written on boot. I've done some general testing and it appears to not change. Can you share why this file is mutated and ends up `@dirty` during `commit_transaction`? I have to add code like this to the `app.rb` to work around it while I test things further. 

```ruby
unless ENV['LAMBY_BUILD']
  require 'bootsnap'
  Bootsnap::LoadPathCache::Store.class_eval do
    def commit_transaction ; end
  end
end
```

**Comment by casperisfine** [comment]
> to simply add something like this to the Dockerfile.

That's pretty much what we do too. Mostly to run `rake assets:precompile` but it generates the load path cache.

> Can you share why this file is mutated and ends up @dirty during commit_transaction?

Hum, that sounds weird. I'd have to dig that up. Not sure I'll have the time today though.

Does your app ever mutate `$LOAD_PATH` ?

**Comment by metaskills** [comment]
Would a different `$LOAD_PATH` on the Docker container vs the Lambda runtime environment cause this? For example, I looked at both and saw these differences.

```
>> d - l
=> ["/var/lang/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib"]
>> l - d
=> ["/var/task", "/var/runtime/lib", "/opt/ruby/lib", "/var/runtime/gems/bundler-2.2.16/lib"]
```

If not, where else could I look to reproduce this?

**Comment by casperisfine** [comment]
> Would a different `$LOAD_PATH` on the Docker container vs the Lambda runtime environment cause this?

Yes. The content of `$LOAD_PATH` is hashed to generate the key. If the `$LOAD_PATH` isn't the same in both environments, the cache won't work.

**Comment by casperisfine** [comment]
> won't work.

I meant a new entry will be written.

**Comment by casperisfine** [comment]
I'd be open to a patch that would ignore the error. That would be inline with recent changes in bootsnap where we make the cache best effort.

**Comment by metaskills** [comment]
Thanks. Done deal. https://github.com/Shopify/bootsnap/pull/358

**Comment by casperisfine** [comment]
I think this was fixed.
