### ISSUE TITLE
bootsnap-1.7.3/lib/bootsnap/load_path_cache/cache.rb:208: warning: Object#untaint is deprecated and will be removed in Ruby 3.2.

### ISSUE THREAD

**Issue by brendon** [Shopify/bootsnap#360]
I'm getting this warning for this line.

https://github.com/Shopify/bootsnap/blob/2d40bd35d42aa262c3c2c479cfc789d0bf172d12/lib/bootsnap/load_path_cache/cache.rb#L208

Is it worth removing now since this is going away anyway?

**Comment by casperisfine** [comment]
That code path should only be executed on older Rubies. What Ruby are you using?

**Comment by casperisfine** [comment]
Hum, apparently it happens on CI as well: https://github.com/Shopify/bootsnap/runs/2447729909#step:5:56

Must be a subtle change in 2.7.3, I'll have a look

**Comment by casperisfine** [comment]
Ok, there's indeed a regression in Ruby 2.7.3... I just can't figure out how it happened though, as there no string change at all in the diff: https://github.com/ruby/ruby/compare/v2_7_2...v2_7_3

**Comment by brendon** [comment]
That's pretty interesting. How are you detecting older rubies in this case?

**Comment by casperisfine** [comment]
I released a 1.7.5 with a fix. 

I still can't explain this regression, but more worrying I can't really explain how it worked on 2.7.2 :/

> How are you detecting older rubies in this case?

I do some feature detection on the behavior of `String#-@`. Recent rubies are smart enough to be able to directly intern the received string if it's already frozen. The code was assuming that if this behavior was not present we'd be on 2.5 or older. Looks like it's not longer the case.

**Comment by brendon** [comment]
Thanks @casperisfine, such fast work! I've deployed it already too :D

Have a great day!
