### ISSUE TITLE
Bootsnap breaks `Ractor.make_shareable`ed proc

### ISSUE THREAD

**Issue by pocke** [Shopify/bootsnap#376]
### I made sure the issue is in bootsnap

Bootsnap changes `Ractor.make_shareable`ed proc's behavior.

### Steps to reproduce

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'bootsnap'
```

```ruby
# test1.rb
require 'bootsnap/setup'
require_relative './test2.rb'
```

```ruby
# test2.rb
x = :foo

pr = Proc.new { p x }

Ractor.make_shareable(pr)

pr.call
```

Put them, then execute `test1.rb`.

### Expected behavior

I expect the outer variable, `x`, is `:foo` as the following

```bash
$ env DISABLE_BOOTSNAP=1 BOOTSNAP_CACHE_DIR=cache bundle exec ruby test1.rb
:foo
```

### Actual behavior

However, actually, the outer variable is `false` as the following.

```bash
$ env BOOTSNAP_CACHE_DIR=cache bundle exec ruby test1.rb
false
```

### System configuration

**Bootsnap version**: 1.9.1

**Ruby version**: I tested with both of the following

* `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]`
* `ruby 3.1.0dev (2021-09-29T23:04:49Z master 565649cfe8) [x86_64-linux]`

**Rails version**:  nothing

### Other notes

I actually realized this problem with OpenStruct. OpenStruct started using `Ractor.make_shareable` since https://github.com/ruby/ostruct/commit/d85639f2f5dffa4fb7428bea2ca918966b6efbad, then my project's CI is failing with the following error message. ref: https://github.com/pocke/rbs_rails/pull/198

```
 rake aborted!
NoMethodError: undefined method `each' for false:FalseClass

        options.rakelib.each do |rlib|
                       ^^^^^
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/rake-13.0.3/lib/rake/application.rb:705:in `raw_load_rakefile'
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
bin/rake:4:in `<main>'
```

**Comment by casperisfine** [comment]
Upstream ticket: https://bugs.ruby-lang.org/issues/18232

**Comment by casperisfine** [comment]
We can close this now it was fixed on ruby-head.
