### ISSUE TITLE
iseq.rb:13 `to_binary`: wrong argument type false (expected Symbol)

### ISSUE THREAD

**Issue by zzak** [Shopify/bootsnap#378]
Having issues with bootsnap on a `rails new --main` application using ruby-dev 3.1.0:

```
ruby -v
ruby 3.1.0dev (2021-11-01T08:48:03Z master b474049c78) [x86_64-darwin20]
```
---
```
./bootsnap-e1882c5993c3/lib/bootsnap/compile_cache/iseq.rb:13:in `to_binary': wrong argument type false (expected Symbol) (TypeError)
  from ./bootsnap-e1882c5993c3/lib/bootsnap/compile_cache/iseq.rb:13:in `input_to_storage'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/compile_cache/iseq.rb:55:in `load_iseq'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  from ./bootsnap-e1882c5993c3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
```
---
```
# gemfile.rb
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

# Use main development branch of Rails
gem "rails", github: "rails/rails", branch: "main"

# The traditional bundling and transpiling asset pipeline for Rails.
gem "sprockets-rails", ">= 2.0.0"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails", ">= 0.3.4"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails", ">= 0.7.11"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails", ">= 0.4.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder", "~> 2.7"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false, github: "Shopify/bootsnap"

# Use Sass to process CSS
# gem "sassc-rails", "~> 2.1"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # Start debugger with binding.b [https://github.com/ruby/debug]
  gem "debug", ">= 1.0.0", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console", ">= 4.1.0"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler", ">= 2.3.3"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver", ">= 4.0.0"
  gem "webdrivers"
end
```

The same thing happened before trying the `github: "Shopify/bootsnap"`, just wondering if this is a known issue or I'm missing something 🤔

**Comment by casperisfine** [comment]
Hi, @zzak, this is indeed a know issue, but with MRI: https://bugs.ruby-lang.org/issues/18250

If you are currently testing ruby-head, it's best to disable ISeq caching for now.

If somehow `3.1.0preview1` releases with this bug, I'll be releasing a new version to automatically do that: https://github.com/Shopify/bootsnap/compare/detect-ruby-3-1-dev-bug

**Comment by casperisfine** [comment]
Actually maybe I should release it now regardless to help people who test against ruby-head.

**Comment by zzak** [comment]
@casperisfine Thanks for the reply! Let me try nobu's patch :)

**Comment by zzak** [comment]
@casperisfine I was able to make it at least this far using the branch, so maybe we can close this one?

![Screen Shot 2021-11-02 at 18 47 36](https://user-images.githubusercontent.com/277819/139824013-0a69752c-2e2d-4242-999d-1a266f4b611d.png)

**Comment by casperisfine** [comment]
We can keep it open as long as the Ruby bug isn't fixed, so that other people looking for it can find it more easily.

**Comment by casperisfine** [comment]
😭 

Ok, I'll have to ship a workaround. Thank you for letting me know.

**Comment by casperisfine** [comment]
The potential less impacting workaround: https://github.com/Shopify/bootsnap/pull/380, I'm just worried it might cause even worse problem, so I'd like to carefully test it first.

**Comment by flanger001** [comment]
Updating to 1.9.3 helped us with this issue. Thanks!

**Comment by casperisfine** [comment]
Welcome. I think we can close this now.

**Comment by noribang** [comment]
Having problems when I run rails db:create using ruby 3.0.4.
Any suggestions?

/usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:13:in `to_binary': wrong argument type false (expected Symbol) (TypeError)
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:13:in `input_to_storage'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:55:in `load_iseq'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/thor-1.1.0/lib/thor.rb:1:in `<main>'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/railties-6.1.3.2/lib/rails/command.rb:7:in `<main>'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/railties-6.1.3.2/lib/rails/commands.rb:3:in `<main>'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/hoon/Development/code/Mod5/002_project_phase_5/phase-5-project-alpha/bin/rails:5:in `<top (required)>'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        from /usr/share/rvm/gems/ruby-3.0.4/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from /home/hoon/Development/code/Mod5/002_project_phase_5/phase-5-project-alpha/bin/spring:10:in `require'
        from /home/hoon/Development/code/Mod5/002_project_phase_5/phase-5-project-alpha/bin/spring:10:in `block in <top (required)>'
        from <internal:kernel>:90:in `tap'
        from /home/hoon/Development/code/Mod5/002_project_phase_5/phase-5-project-alpha/bin/spring:7:in `<top (required)>'
        from bin/rails:2:in `load'
        from bin/rails:2:in `<main>'
