### ISSUE TITLE
The same cache seems used for different Ruby versions

### ISSUE THREAD

**Issue by eregon** [Shopify/bootsnap#384]
Before https://github.com/Shopify/yjit-bench/pull/69#pullrequestreview-843427951 I and @noahgibbs noticed that Bootsnap has an invalid cache when running the `erubi_rails` benchmark with e.g. 3.1-dev, 3.1.0 and 3.0.x.
It seems the cache is not separated per Ruby version.

`rm -rf tmp/cache/bootsnap` is a workaround, but hard to remember, and the error can be [quite confusing](https://github.com/Shopify/yjit-metrics/issues/119#issuecomment-990812163).

Should bootsnap care about this?
It seems not so uncommon to use e.g. different Ruby releases to run a Rails app, and Rails seems to just use the default bootsnap cache path.

One issue is if CRuby dev versions are "supported" they report the same RUBY_VERSION even though many things including the ABI, the stdlib files, the bytecode format, etc might change. Maybe using RUBY_REVISION (the commit) is the only safe way then.

**Comment by casperisfine** [comment]
👋 the ruby version is collected here: https://github.com/Shopify/bootsnap/blob/a0aa3d2b0cbdcef9d8db9ae787c3628ac250780f/ext/bootsnap/bootsnap.c#L246-L264

It's basically `RUBY_REVISION`. 

If you think there's a better key, I'm totally open to update it.

**Comment by eregon** [comment]
Using `RUBY_REVISION` should be enough, although here a Hash of it is used.
What's the expected behavior if the `RUBY_REVISION` does not match when using bootsnap, e.g., in a Rails app?
I wonder if the issues we were hitting are maybe not guarded by that check/hash (e.g., the known stdlib files as in https://github.com/Shopify/yjit-metrics/issues/119#issuecomment-990812163).
Or maybe the hash of the revision isn't good enough, but that sounds not so likely.

**Comment by casperisfine** [comment]
> What's the expected behavior if the RUBY_REVISION does not match when using bootsnap, e.g., in a Rails app?

The cache entry contain a "version" header. If the header doesn't match, it acts as a cache miss and is regenerated.

> I wonder if the issues we were hitting are maybe not guarded by that check/hash

I think you are right, that file was extracted in 3.1: https://github.com/ruby/ruby/commit/12a0a89e22fbc312e4a95a7749bc153532daa855

The version guard is only for the compile cache (iseq etc). I think the error you did hit was a load path cache, which doesn't have such guard (IIRC). I'll try to dig a bit more into it later on (just got back from vacations, so I have tons of things to deal with first).
