### ISSUE TITLE
Investigate dropping the load path cache at the end of boot 

### ISSUE THREAD

**Issue by casperisfine** [Shopify/bootsnap#386]
Something I wanted to do for a while and that @SamSaffron reminded me of: https://bugs.ruby-lang.org/issues/18454#note-5

For big applications, the load path cache can be quite big. But in production mode, most apps shouldn't need it once the boot sequence is over. 

So we should look at freeing it at the end of eager load (pre-fork).

**Comment by SamSaffron** [comment]
I think just providing an API for releasing the index is probably fine as a first step, cause we could just wire it into our last Rails initializer. 

`Bootsnap.dispose_index` perhaps?

**Comment by casperisfine** [comment]
Yes that's trivial. But I'd like to see if we could provide a `Railtie` to do this automatically so that all users benefit from it and not just a tiny minority. That's why I need to dig a bit more.
