### ISSUE TITLE
I am facing this problem while running "msfconsole"

### ISSUE THREAD

**Issue by RRA876** [Shopify/bootsnap#408]
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- net/ftp (LoadError)

**Comment by casperisfine** [comment]
That isn't a bootsnap problem. `net/ftp` used to be a default gem until Ruby 3.0, and was removed in Ruby 3.1.

You have to add `gem "net-ftp"` to your gemfile (or if you don't have a Gemfile run `gem install net-ftp`).

Please report this to the `msfconsole` project.

**Comment by casperisfine** [comment]
See: https://github.com/rapid7/metasploit-framework/issues/16080
