### ISSUE TITLE
Cache key when using musl libc (eg Alpine linux)

### ISSUE THREAD

**Issue by dhagher** [Shopify/bootsnap#409]
When not using glibc, cache key is based on `uname -v` leading to the same problems when bundling cache as described in https://github.com/Shopify/bootsnap/pull/283
This makes bootsnap significantly less useful for container workloads when [Alpine Linux](https://alpinelinux.org) is used.

### Steps to reproduce
Run on non glibc system, eg Alpine Linux using docker
```FROM ruby:3.1.1-alpine3.15```

### Expected behavior
Cache precompiled and stored in the container, eg
```RUN bootsnap precompile --gemfile```
should be valid on other hosts.

### Actual behavior
Due to lack of `__GLIBC__`,  cache key depends on kernel version https://github.com/Shopify/bootsnap/blob/main/ext/bootsnap/bootsnap.c#L294
Based on https://wiki.musl-libc.org/faq.html#Q:-Why-is-there-no-%3Ccode%3E__MUSL__%3C/code%3E-macro? I think there is no similar way to check for musl version.

### System configuration

**Bootsnap version**: 1.10.3

**Ruby version**: 3.1.1

**Comment by casperisfine** [comment]
Hum, to be honest I don't quite get why we use such a precise cache key.

At first sight `RUBY_DESCRIPTION` should plenty precise for instruction sequences and load path caches but I might be wrong.

Git blame point to https://github.com/Shopify/bootsnap/pull/43:

```
 * The idea here is that we want a cache key member that changes when the OS
 * changes in such a way as to make existing compiled ISeqs unloadable.
 *
 * On Darwin and FreeBSD, this is the kernel version, since that tends to vary
 * with whole-system upgrades. What we probably care about more is the libc
 * version, which is what we explicitly ask for on linux.
 * (and KERN_OSRELEASE came back empty for me one one linux box, so...?)
 *
 * I'm kind of guessing about the important factors here. We could probably do
 * this better.
```

I'll try to consult a few people to see if we could drop theses from the cache key.

**Comment by casperisfine** [comment]
From a colleague:

> The code bit casts ints and stuff, so endianness matters and maybe different on 32b versus 64b as well.

But I don't think `__GLIBC__ ` actually covers that.

**Comment by dhagher** [comment]
for checking endianness in ruby I see suggestions to compare `pack("I")` with `pack("N")` which translates to a runtime cast check https://github.com/ruby/ruby/blob/ruby_3_1/pack.c#L59

>Also after a quick chat with Burke, it seems this was mostly a conservative decision. So I'll look into removing some elements from the cache key.

I understand that it's much better not to reuse the cache than to load incompatible code, however isn't using a container on the same architecture sufficient to be compatible? Looking at `RubyVM::InstructionSequence` binary format is clearly noted as not portable but I have trouble figuring out what exactly it depends on.

Thank you very much for your help and a great gem

**Comment by casperisfine** [comment]
> Looking at `RubyVM::InstructionSequence` binary format is clearly noted as not portable but I have trouble figuring out what exactly it depends on.

Well, it's definitely not portable between Ruby versions, then wether Ruby was compiled in 32 or 64bit, but I guess it's part of the arch, and yes, the arch. So I'm thinking `RUBY_VERSION + RUBY_PLATFORM` should be enough.
