### ISSUE TITLE
Does not play nice with docker

### ISSUE THREAD

**Issue by neilgupta** [Shopify/bootsnap#41]
The way bootsnap considers anything in the ruby distribution path to be stable is causing problems for our docker setup, and I expect it's a common setup for many ruby docker environments.

If you install ruby on ubuntu with the `brightbox/ruby-ng` aptitude PPA, it sets the install prefix to `/usr`. However, in docker, your app path is generally `/usr/src/app/...`. Since bootsnap considers anything that falls in `RbConfig::CONFIG['prefix']` to be stable, the entire rails app gets marked as stable, which means any path change or new file requires a manual purge of the cache.

The easiest fix is probably to whitelist `usr/src/app` as a volatile path.

**Comment by burke** [comment]
What's your `RbConfig::CONFIG['libdir']`? Maybe the most sensible thing is to just use that instead of prefix.

**Comment by neilgupta** [comment]
That would work. In docker, that returns `/usr/lib` which would avoid this problem. On macOS, that does limit the ruby distribution path to just the lib directory. If there's anything else being required from the distribution (not sure, `bin` perhaps?), then it won't get cached, but I think that's a reasonable middle ground.

**Comment by burke** [comment]
Ok, that'll work then. I'm not aware of anything being required outside of libdir. I've already committed it to master, so it'll be in 0.3.1, which I imagine should be in the next couple of days. Thanks :)
