### ISSUE TITLE
Cannot start Rails application in 1.11.0

### ISSUE THREAD

**Issue by tagliala** [Shopify/bootsnap#411]
### I made sure the issue is in bootsnap

```
$ DISABLE_BOOTSNAP=1 rails s
=> Booting Puma
=> Rails 7.0.2.2 application starting in development 
```

git bisect identified the following commit: 4f604082f54a0e9dd45cbeabe2f9cedf0e13fe6c

### Steps to reproduce
1. `rails new test-bootsnap -G -J -T`
2. `cd test-bootsnap`
3. `rails s`

### Expected behavior
Server starts

### Actual behavior
```
$ rails s
~/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.11.0/lib/bootsnap/load_path_cache/store.rb:44:in `set': can't modify frozen Hash: {"__bootsnap_ruby_version...
```

### System configuration

**Bootsnap version**: 1.11.0

**Ruby version**: 3.0.3

**Rails version**: 7.0.2.2

**Comment by georf** [comment]
Same with Rails 6.1.4.6

**Comment by OrceMaceski** [comment]
Yes, bump to version 1.11.0 breaks rails default conf for me too.

**Comment by uxxman** [comment]
same error

ruby: 3.1.0
rails: 7.0.2.2
bootsnap: 1.11.0

**Comment by cpjmcquillan** [comment]
Same error

Ruby: 2.6.9
Rails: 6.0.4
Bootsnap: 1.11.0
