### ISSUE TITLE
Uninitialized constant error when Bundler.require is used before booting Rails app with Grape

### ISSUE THREAD

**Issue by guigs** [Shopify/bootsnap#416]
The error only happens when booting a Rails app in a particular way (sidekiqswarm) when loading a nested class whose parent class inherits from `Grape::API`. `Grape::API` implements [`inherited`](https://github.com/ruby-grape/grape/blob/75276be92431527791c40068fccb9bacb131d06b/lib/grape/api.rb#L35-L40) and [`const_missing`](https://github.com/ruby-grape/grape/blob/75276be92431527791c40068fccb9bacb131d06b/lib/grape/api.rb#L85-L91), which is probably causing the issue.

For example:

```ruby
# app/api/thing.rb
class Thing < Grape::API; end

# app/api/thing/nested_thing.rb
class Thing
  class NestedThing; end
end
```

sidekiqswarm boots the applications doing something similar to:

```ruby
require 'bundler/setup'
Bundler.require('default')
require 'rails'
require File.expand_path('./config/environment.rb')
```

### I made sure the issue is in bootsnap

The problem does not persist if `DISABLE_BOOTSNAP=1` or `DISABLE_BOOTSNAP_LOAD_PATH_CACHE=1` is used.

### Steps to reproduce

I've created a minimum Rails app to demonstrate the problem: https://github.com/heyjobs/grapeboot

### Expected behavior

Application is booted correctly.

### Actual behavior

Application crash with

```
/home/guigs/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/grape-1.6.2/lib/grape/api.rb:87:in `const_get': uninitialized constant #<Class:0x00007f5b1c6cb2d0>::NestedThing (NameError)
Did you mean?  MyApi::Thing::NestedThing
        from /home/guigs/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/grape-1.6.2/lib/grape/api.rb:87:in `const_missing'
        from /home/guigs/grapeboot/config/routes.rb:8:in `block in <main>'
        from /home/guigs/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:428:in `instance_exec'
        from /home/guigs/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:428:in `eval_block'
        from /home/guigs/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:410:in `draw'
        from /home/guigs/grapeboot/config/routes.rb:1:in `<main>'
        from /home/guigs/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
```

### System configuration

**Bootsnap version**: 1.11.1 (also tested with 1.9.4)

**Ruby version**: 3.0.3 (also tested with 2.7.3)

**Rails version**: 7.0.3 (also tested with 6.1.5)

### Other info/questions

Here's related sidekiq issue: https://github.com/mperham/sidekiq/issues/5346

The error does not happen if `require 'bootsnap/setup'` is called before `Bundler.require('default')`. Even though one should usually do that, calling `Bundler.require('default')` before loading the app should't cause any errors, should it?

Is there anything to be fixed in the way sidekiqsarm boots the application and/or in how `Grape::API` implements `inherited`/`const_missing`?

**Comment by casperisfine** [comment]
Thank you for the repo repo. I've dug quite a bit already and must admit I'm quite puzzled.

What I found so far, editing the `routes.rb`, and removing the grape `const_missing` that just adds to the confusion:

```ruby
  p [:ref_thing]
  Thing
  p [:thing_loaded]
  p Thing.const_defined?(:NestedThing)
  p Thing.autoload?(:NestedThing)
  Thing::NestedThing
```

```
[:ref_thing]
Loading Thing
Zeitwerk@rails.main: autoload set for Thing::NestedThing, to be loaded from /Users/byroot/src/github.com/heyjobs/grapeboot/app/api/thing/nested_thing.rb
Zeitwerk@rails.main: constant Thing loaded from file /Users/byroot/src/github.com/heyjobs/grapeboot/app/api/thing.rb
[:thing_loaded]
false
nil
/Users/byroot/src/github.com/heyjobs/grapeboot/config/routes.rb:13:in `block in <main>': uninitialized constant Thing::NestedThing (NameError)
```

So `Zeitwerk` did set the autoload according to its logs, but somehow it not there.

I'll keep digging.

**Comment by casperisfine** [comment]
@guigs, forgot to mention:

>  calling Bundler.require('default') before loading the app should't cause any errors, should it?

No it shouldn't cause errors, but however it means that most of your dependencies are loaded without bootsnap enabled, so you're passing up on some boot time improvements. So I'd recommend against doing this either way.

But I don't know about your use case so...

**Comment by guigs** [comment]
@casperisfine Thanks for your investigation and quick fix!

@mperham Consider the above comment for sidekiqswarm.
