### ISSUE TITLE
Implement read only mode

### ISSUE THREAD

**Issue by ChrisBr** [Shopify/bootsnap#423]
Implement a read only mode which does not update the bootsnap cache anymore e.g by supplying an env variable `BOOTSNAP_READ_ONLY`.

## Background

Our Bootsnap cache in CI is quite significant and we run several CI workers on the same machine via docker. As bootsnap keeps writing to the cache, we need to keep a dedicated copy of the cache for each of our CI worker instances. If bootsnap would support a read only mode, we could only keep one copy of the cache around and mount it into the containers in read only mode. This would reduce our network traffic, I/o and disk size significantly.

**Comment by casperisfine** [comment]
Ack. I think that would make sense, even beyond the use case you mention.

It may take me a tiny while before I can look into this (couple weeks perhaps).
