### ISSUE TITLE
/usr/share/ruby/time.rb is not `.stable?` - path_test.rb failing

### ISSUE THREAD

**Issue by voxik** [Shopify/bootsnap#431]
This is basically dupe of #173, but since it was closed without resolution, I am to going to file this issue again.

The problem is this failing test:

~~~
  1) Error:
Bootsnap::LoadPathCache::PathTest#test_stability:
NoMethodError: undefined method `pry' for #<Binding:0x00007f34f6608c90>
    /builddir/build/BUILD/bootsnap-1.15.0/usr/share/gems/gems/bootsnap-1.15.0/test/load_path_cache/path_test.rb:25:in `test_stability'
~~~

And I think the issue is in this line:

https://github.com/Shopify/bootsnap/blob/b6107b8c16ed6a0748386bd8f409f0f944eac767/lib/bootsnap/load_path_cache/path.rb#L128

So the path in question is:

~~~
[1] pry(#<Bootsnap::LoadPathCache::PathTest>)> p stable
#<Bootsnap::LoadPathCache::Path:0x00007fb3fa26dfa8 @path="/usr/share/ruby/time.rb", @real=false>
=> #<Bootsnap::LoadPathCache::Path:0x00007fb3fa26dfa8 @path="/usr/share/ruby/time.rb", @real=false>
~~~

while these are the paths used to match:

~~~
[2] pry(#<Bootsnap::LoadPathCache::PathTest>)> p RbConfig::CONFIG["libdir"]
"/usr/lib64"
=> "/usr/lib64"
[3] pry(#<Bootsnap::LoadPathCache::PathTest>)> p RbConfig::CONFIG["sitedir"]
"/usr/local/share/ruby/site_ruby"
=> "/usr/local/share/ruby/site_ruby"
~~~

The issue here is that the Ruby configuration allows more flexibility then the code assumes, therefore the file in question is wrongly marked as instable. That could probably lead to some other wrong assumptions made by Bootsnap, dunno.

**Comment by voxik** [comment]
I'd submit fix for this, but the question is what is the real intent? What is considered stable?

Given that the comment says: "Built-in ruby lib stuff doesn't change, but things can occasionally be installed into sitedir, which generally lives under libdir.", then there should probably be matched `libdir` as well as `datadir`.

Another option could be to match `rubylibdir` instead. That way, the exception for `sitedir` could be probably dropped, not sure.

BTW this issue is reproducible on Fedora.

**Comment by casperisfine** [comment]
Thanks for the report. I'll need to dig into the history a bit to see what this stable thing is about.

**Comment by casperisfine** [comment]
>  but the question is what is the real intent? What is considered stable?

Ok, so "stable" here is to describe code that come from either the stdlib or gems, as opposed to your application code.

So anything coming from the ruby installation can be considered stable.

> I'd submit fix for this

Please do if the above clarified your question.

**Comment by voxik** [comment]
But the code currently assumes that everything, what is basically under `/usr/lib64` is stable, with possible exception to `sitedir`. On standard distribution, that might include large variety of files, i.e. majority of the distribution of the context. If that was the intention, then this should also include the `/usr/share`.

But I'm going to assume, that intention was to include just Ruby StdLib.

**Comment by voxik** [comment]
Also, I am not Bootsnap expert, so the question is, if only Ruby files needs to be covered or if also arch specific files (.so libraries) should be included.

**Comment by voxik** [comment]
I'm going assume the former.

**Comment by casperisfine** [comment]
Yeah `.so` files should be included.
