### ISSUE TITLE
Contributing speed improvements to Ruby?

### ISSUE THREAD

**Issue by hakunin** [Shopify/bootsnap#44]
It looks like the optimizations here might be benefitial for all ruby apps.

Have you opened issues to add some of these features to the language itself?

**Comment by jules2689** [comment]
We have looked into the possibility and discussed this with relevant people. The features require configuration past initial Ruby installations and assume a few things that Ruby does not. For these reasons, we don't see this as an appropriate fit for core Ruby at this time - but we are not closing the door on this possibility.

For starters, `bootsnap` will be included in all new Rails Gemfiles by default. :)

**Comment by burke** [comment]
Oh, speaking of that -- @rafaelfranca, we've fixed all the issues now that I feel are major blockers to including it in rails. It should work on any linux/darwin/freebsd. Windows support is still not there but ¯\\\_(ツ)\_/¯

**Comment by rafaelfranca** [comment]
@burke I was waiting your PR to Rails! I think the credits for including it there by default should go to you and @jules2689, so I don't want to do it 😄.

**Comment by burke** [comment]
Alright then! https://github.com/rails/rails/pull/29313

**Comment by burke** [comment]
I don't think it's reasonable to force this level of caching on ruby itself, but the rails PR is open now. Closing this.
