### ISSUE TITLE
undefined method `driver_path=' for Selenium::WebDriver::Chrome:Module

### ISSUE THREAD

**Issue by andrisole92** [Shopify/bootsnap#453]
### Steps to reproduce
Upgraded rails 6 to rails 7

Running any command gives me:

```
NoMethodError: undefined method `driver_path=' for Selenium::WebDriver::Chrome:Module

Selenium::WebDriver::Chrome.driver_path=Gem.bin_path("chromedriver-helper","chromedriver-helper")
                           ^^^^^^^^^^^^^
/Users/andrejsruz/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
```
### Expected behavior
Expect commands to run as expected
### Actual behavior
Receiving error

### System configuration
MacOS
**Bootsnap version**:
1.16.0
**Ruby version**:
3.1.2
**Rails version**: 
7.0.0

**Comment by casperisfine** [comment]
This has nothing to do with Bootsnap: https://github.com/SeleniumHQ/selenium/commit/c9fe4923275f7d946c667cb28594bef7a1e488a3
