### ISSUE TITLE
Caching tmp/cache/bootsnap-load-cache on CI

### ISSUE THREAD

**Issue by arunthampi** [Shopify/bootsnap#47]
Should we be saving/restoring `tmp/cache/bootsnap-load-path-cache` across CI runs? We're splitting up our tests and running it across multiple containers.

Will the contents of `tmp/cache/bootsnap-load-path-cache` be the same across all of them?

**Comment by burke** [comment]
You definitely can if you feel like the savings is worth the juggling to wire it up. There shouldn't be anything in there that makes that not-work, as long as things are installed to the same paths on each machine. I

**Comment by arunthampi** [comment]
@burke cool thanks
