### ISSUE TITLE
What is MY_ENV?

### ISSUE THREAD

**Issue by amcaplan** [Shopify/bootsnap#48]
The standard setup code shown in the README includes the line:

```ruby
development_mode:     ENV['MY_ENV'] == 'development',
```

Is `MY_ENV` something used in Shopify?  Was the intention to refer to `ENV['RAILS_ENV']`?

I mention this not just because I want to be sure, but because chances are a lot of people will do what I initially did, i.e. copypaste without thinking too much, and not notice that `MY_ENV` was meant to be replaced with something else, leading to `development_mode` always being `false`.

**Comment by burke** [comment]
Yeah, the idea is to encourage you to think about what the definition of "development mode" is for your application, without assuming rails. Realistically, it probably makes sense to just assume rails though.

**Comment by jules2689** [comment]
I hope this commit reduces confusion https://github.com/Shopify/bootsnap/commit/05c00dbc802813ded9460c5773950123df6dd30b

:)

Please re-open if you think this can be improved more
