### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by mttkay** [Shopify/bootsnap#490]
Would it be possible to get a new patch release?

This issue has been plaguing us for months now and is fixed in this unreleased commit: https://github.com/Shopify/bootsnap/commit/9210a2e4b5eb5c84ccd6f64807a8b4ce3a668438

Thank you! <3

**Comment by casperisfine** [comment]
https://github.com/Shopify/bootsnap/commit/cae219a7aa57370951e36c010db6e8e2408543e7
