### ISSUE TITLE
Reset cache?

### ISSUE THREAD

**Issue by stereobooster** [Shopify/bootsnap#53]
At some point it seemed to me that bootsnap cached ruby paths and I found no way to reset cache except recreate new server from scratch.

Is there a way to reset bootsnap cache?

**Comment by jules2689** [comment]
During `bootsnap` initialization (since v0.3.2), you set a `cache_dir` during initialization. Within that directory is `bootsnap-load-path-cache` which contains the load path cache.

Deleting that should reset the cache for load paths, you could also delete the cache dir you specified.

**Comment by stereobooster** [comment]
makes sense. Thanks
