### ISSUE TITLE
Setup.rb missing from 1.0

### ISSUE THREAD

**Issue by exadeci** [Shopify/bootsnap#59]
There is no `lib/bootsnap/setup.rb` in the release tagged 1.0:
https://github.com/Shopify/bootsnap/tree/dc29efb55cf5ac595dbb0aeb99c8d3172da9ed56/lib/bootsnap

So the gem can't be used, I had to get it from github.

**Comment by exadeci** [comment]
NVM I should have followed the release Readme and not Master

**Comment by burke** [comment]
You can use 1.1.0.pre if you'd like. I'll probably release that was 1.1.0 tomorrow.
