### ISSUE TITLE
using bundle --standalone make bootsnap slow

### ISSUE THREAD

**Issue by grosser** [Shopify/bootsnap#62]
I was playing around with 

```
bundle install --standalone

# require 'bundler/setup' ->
require 'bundler'
require './vendor/bundle/bundler/setup.rb'
def gem(*);end
```

the time it takes to reach "after require bundler" is significantly faster (1s -> 0.2s), but overall boot time suffers ... so I'm thinking that there are optimizations done in bootsnap that somehow now stop working ... this might be an interesting approach to solving https://github.com/Shopify/bootsnap/issues/16

for a playground app: https://github.com/zendesk/samson/pull/2081

/fyi @FooBarWidget @jules2689 @burke

**Comment by jules2689** [comment]
@grosser this sort of makes sense. In this case, we can't consider `bundler` to be a stable cache since it is under your application directory. Similarly, bundler would install gems in the vendor cache and we therefore would also not consider that a "stable" cache.

This is just a theory right now, I didn't verify anything. I think what we could try to do is to allow a user to specify paths within their application to consider stable (such as `./vendor/bundle`).

WDYT @burke

**Comment by grosser** [comment]
that sounds good ... any hacky way I could achive this to sanity check if it works ?
... could finally have sub 1s boot time 🔥

**Comment by jules2689** [comment]
For sure, this method [here](https://github.com/Shopify/bootsnap/blob/b197d081966d4ee17c5db9e6ff521965f0537d81/lib/bootsnap/load_path_cache/path.rb#L98-L108) is how we detect if something is "stable" or "volatile". In there you have `expanded_path` which is the absolute path of the file. You could put in an extra if/else that is basically `elsif expanded_path.start_with?(PATH_TO_VENDORED_BUNDLER); STABLE [...]` then you could hackily check this theory :)

Please post any results you get!

**Comment by grosser** [comment]
1s down :D
It's a bit brittle and tricky to use ... but shows promise ...

 - get rid of Bundler.require usage
 - override gem method to noop
 - using standalone leaves regular gems requireable, so we'd need to fix
that too ... maybe a bundler bug ...
 - I used expanded_path.include?("vendor/bundle") in my bootsnap patch,
ideally would use .start_with and a full path

we don't really need this `standalone` from bundler ... could just somehow
cache all the state that Bundler.setup produces ... would be much simpler
to use and nobody needs to change their app.

**Comment by jules2689** [comment]
> using standalone leaves regular gems requireable, so we'd need to fix that too ... maybe a bundler bug ...

Not too sure what you mean by this part. Could you clarify? :)

**Comment by grosser** [comment]
you can still require any globally installed gem since `Bundler.setup` is
not called when using `setup.rb` ... not something we have to worry about
if we can cache bundler state though ...

**Comment by jules2689** [comment]
Ah, ok. I spoke with some other Bundler people and this is the explanation "That’s intentional when using standalone. Standalone is entirely standalone from Bundler & RubyGems."

So what you're seeing there is expected. Moreover "standalone is literally just `$LOAD_PATH` manipulation", which means we may be hard pressed to find a solution here since that is what bootsnap does as well. I'll speak with @burke and get back to you :)

**Comment by grosser** [comment]
Yeah, I'd think it's easiest to cache bundler state ...
otherwise a patch to bundler to somehow make it faster / cache load-paths
would be nice ...

**Comment by jules2689** [comment]
> otherwise a patch to bundler to somehow make it faster / cache load-paths would be nice ...

I've looked into this, and it's not trivial or easy. At minimum, I'd wait for Bundler 2.x

**Comment by burke** [comment]
@jules2689 asked for my input... lots of different things going on in this thread, but one thing in particular I think we should address:

I would argue that it's probably reasonable to consider the `Bundler.bundle_path`"stable", regardless of whether it's the default or a vendor directory. 

```diff
diff --git a/lib/bootsnap/load_path_cache/path.rb b/lib/bootsnap/load_path_cache/path.rb
index 269dc43..f5291f6 100644
--- a/lib/bootsnap/load_path_cache/path.rb
+++ b/lib/bootsnap/load_path_cache/path.rb
@@ -99,6 +99,8 @@ module Bootsnap
         @stability ||= begin
           if Gem.path.detect { |p| expanded_path.start_with?(p.to_s) }
             STABLE
+          elsif expanded_path.start_with?(Bundler.bundle_path.to_s)
+            STABLE
           elsif expanded_path.start_with?(RUBY_LIBDIR) && !expanded_path.start_with?(RUBY_SITEDIR)
             STABLE
           else
```

Thoughts?

**Comment by grosser** [comment]
sounds good to me!

**Comment by burke** [comment]
Should be fixed, please reopen if it's still slow.
