### ISSUE TITLE
Bundler::GemRequireError on production

### ISSUE THREAD

**Issue by jvenezia** [Shopify/bootsnap#76]
During a deploy using Capistrano, we have `Bundler::GemRequireError` errors. It's not always the same gem, not always in the same Capistrano task.

Here is a backtrace of one error: https://pastebin.com/aMcykz4x

So we are enabling bootsnap only on development and test environments for now.

**Comment by burke** [comment]
I believe this was recently fixed: https://github.com/Shopify/bootsnap/issues/104
