### ISSUE TITLE
Bootsnap does not work with version of msgpack from git

### ISSUE THREAD

**Issue by simon-shopify** [Shopify/bootsnap#79]
I was trying a branch of msgpack on Shopify core, but the application just did not want to start. I found out that the cause was that [`ExplicitRequire`](https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/explicit_require.rb#L25-L42) relies on the fact that the gem has the same name as it's path. It is not the case with msgpack, since the gem is called `msgpack`, but the repo is `msgpack-ruby`.

I was able to make it start with this patch:
```ruby
require "bootsnap/explicit_require"
Bootsnap::ExplicitRequire.singleton_class.prepend(Module.new do
  def with_gems(*gems, &body)
    super(
      *gems.map do |gem|
        case gem
        when "msgpack" then "msgpack-ruby"
        else gem
        end
      end,
      &body
    )
  end
end)
```

I don't know if there is a way to map the name of a gem back to the folder where it is stored?

**Comment by burke** [comment]
Hm, yeah, maybe we should loosen up the matching to only look for `.include?("/#{gem")`

**Comment by simon-shopify** [comment]
> Hm, yeah, maybe we should loosen up the matching to only look for .include?("/#{gem")

That would only work if the gem is a prefix of the repo, `ruby-msgpack` would break.

**Comment by burke** [comment]
I guess the other solution would be to just try this and fall back to the full `$LOAD_PATH` if it gets a `NameError`

**Comment by simon-shopify** [comment]
No super elegant, but that would work! Though it's a pretty minor issue, so I'm not even sure it's worth fixing in this case. Maybe we could just document this limitation and have users make a git mirror with the same name as the gem if they really want to do that.
