### ISSUE TITLE
Cache issue after deleting one gem

### ISSUE THREAD

**Issue by benoittgt** [Shopify/bootsnap#80]
Hello

I removed one gem from my gemfile but when I run the app...
```sh
$ bundle exec rspec
Run options: --seed 46427
/Users/bti/.rvm/gems/ruby-2.4.1@app/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require': cannot load such file -- emm_pubsub (LoadError)
```

As mention here https://github.com/Shopify/bootsnap/issues/53

I removed the cache folder in `tmp` (I have the default config). But I still have the issue. Do you have any idea how to fix it?

**Comment by burke** [comment]
Is emm_pubsub the gem you removed? Where is it being required from? If you've removed the cache, there should be no way your application still knows about that gem other than any place it's being explicitly (or implicitly) required.

**Comment by benoittgt** [comment]
My bad. This is completely unrelated.
