### ISSUE TITLE
Intermittent segmentation faults on Circle CI

### ISSUE THREAD

**Issue by bslobodin** [Shopify/bootsnap#87]
Yesterday we saw a number of builds fail with a seg fault, that is seemingly related to bootsnap. It was inconsistent at best, but happened on a number of unrelated builds. I'd be happy to share more logs, if you think those would help?

```
/home/circleci/project/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/store.rb:72: [BUG] Segmentation fault at 0x00000000000033
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0045 p:---- s:0201 e:000200 CFUNC  :dump
c:0044 p:0078 s:0197 e:000194 METHOD /home/circleci/project/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/store.rb:72
c:0043 p:0015 s:0191 e:000190 METHOD /home/circleci/project/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/store.rb:53
c:0042 p:0038 s:0188 e:000186 METHOD /home/circleci/project/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/store.rb:45
c:0041 p:0011 s:0184 e:000183 METHOD /home/circleci/project/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/cache.rb:140
c:0040 p:0070 s:0180 e:000179 BLOCK  /home/circleci/project/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/cache.rb:123 [FINISH]
c:0039 p:---- s:0178 e:000177 CFUNC  :synchronize
```

💾 [build12502.log](https://github.com/Shopify/bootsnap/files/1337396/build12502.log)

**Comment by casperisfine** [comment]
So the backtrace indicates the issue is likely inside `MessagePack.dump` https://github.com/Shopify/bootsnap/blob/d84bf7af24a7ef7783b96772db0fdbba45b7bca4/lib/bootsnap/load_path_cache/store.rb#L72

What version of message pack are you using? Because bootsnap requires `~> 1.0`, so there is many compatible versions.

**Comment by casperisfine** [comment]
Nvm, I found it in the dump: `msgpack-1.1.0`

**Comment by bslobodin** [comment]
We've since disabled Bootsnap in CI for Bourgeois. It was still segfaulting once in a while.

**Comment by ahuth** [comment]
Looks like msgpack fixed a segfault. Not sure if its the same one referenced here or not, but [note the changelog notes for v1.2.2](https://github.com/msgpack/msgpack-ruby/blob/master/ChangeLog).

**Comment by burke** [comment]
Haven't heard about this in ages, probably that was the fix.
