### ISSUE TITLE
unmatched platform 😩

### ISSUE THREAD

**Issue by niclin** [Shopify/bootsnap#92]
System: OSX High Sierra 10.13.1
ruby-version : 2.4.1

When I run my project always show following error message

```
unmatched platform for file /Users/Nic/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/yaml.rb
rake aborted!
unmatched platform
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/compile_cache/iseq.rb:18:in `load_from_binary'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/compile_cache/iseq.rb:18:in `storage_to_output'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/compile_cache/yaml.rb:36:in `install!'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/compile_cache.rb:11:in `setup'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap.rb:29:in `setup'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/setup.rb:39:in `<top (required)>'
/Users/Nic/Dropbox/projects/business/growthschool/otcbtc/config/boot.rb:4:in `require'
/Users/Nic/Dropbox/projects/business/growthschool/otcbtc/config/boot.rb:4:in `<top (required)>'
/Users/Nic/Dropbox/projects/business/growthschool/otcbtc/config/application.rb:1:in `require_relative'
/Users/Nic/Dropbox/projects/business/growthschool/otcbtc/config/application.rb:1:in `<top (required)>'
/Users/Nic/Dropbox/projects/business/growthschool/otcbtc/Rakefile:4:in `require_relative'
/Users/Nic/Dropbox/projects/business/growthschool/otcbtc/Rakefile:4:in `<top (required)>'
/Users/Nic/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/Users/Nic/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Nic/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

Try google `unmatched platform bootsnap` but not find good result to resolve my problem.

Start rails server success when I comment out the `require "bootsnap/setup"
` but is not good idea.

How can I resolve this problem?

**Comment by rafaelfranca** [comment]
Looks like the Ruby version that wrote the cache is different from the ruby version that is reading from the cache. Maybe we should put the Ruby platform as part of the cache key?

**Comment by niclin** [comment]
@rafaelfranca 

OK, I has been resolve this problem.

Because my project using dropbox sync to multiple computer(work & home), the cache file generate from workplace devise(iMac), so the cache is not match my home devise(MacBook).

Now, I can start rails server successful when I delete `tmp/bootsnap-compile-cache` 

But I think maybe we can improve this problem?

**Comment by rafaelfranca** [comment]
Yeah. Maybe we can use the platform in the cache key.

**Comment by burke** [comment]
So... this is still puzzling.

We are encoding in the cache key:

* `os_version`: an indicator of the version of the OS (n for Sierra; n+m for High Sierra)
* `ruby_revision` (`RUBY_REVISION`): an integer representation of RUBY_VERSION.

The `os_version comes, more or less, from `uname -r`. The only way I can see this breaking is if two different OSes somehow had the same version number.

**Comment by burke** [comment]
It looks like the error is ultimately generated here: https://github.com/ruby/ruby/blob/trunk/compile.c#L9389-L9391
