### ISSUE TITLE
disable_trace option addressed in ruby-core trunk

### ISSUE THREAD

**Issue by methodmissing** [Shopify/bootsnap#93]
See https://bugs.ruby-lang.org/issues/14104

**Comment by burke** [comment]
> a. Big overhead to turn on/off TracePoint because we need to modify all of existing ISeqs.

This is horrifying.

**Comment by ViugiNick** [comment]
This change in Ruby 2.5.0 makes it impossible to debug the rails application with bootsnap. Most likely this is due to the fact that the bootcamp caches the frames before the trace flags was set.
https://youtrack.jetbrains.com/issue/RUBY-20684

**Comment by burke** [comment]
I deeply resent this change to MRI, but there's not much I can do other than that. This is a bug in MRI.

**Comment by SamSaffron** [comment]
Can you expand on this a bit I would like to work with Koichi to find a solution here.

Just flipping `disable_trace` does not seem to resolve this? Should it explicitly compile with `{ trace_instruction: true }` unless you specify `disable_trace: false` ?

**Comment by ViugiNick** [comment]
@burke It seems to me that this problem can be fixed at the bootsnap level too. For example it's possible to add something like rb_iseq_trace_set(iseq, ruby_vm_event_enabled_flags & ISEQ_TRACE_EVENTS); in the `succeed` section of the bs_fetch

**Comment by burke** [comment]
I'm open to merging a few varieties of imaginable workaround for this. I'm not particularly attached to the `disable_trace` feature in the first place. We don't even really use it at Shopify.

Pulling in extra headers and munging MRI's internal state, etc., is fair game as long as it doesn't break older versions and the path to fixing when future releases happen is clearly documented alongside the code.

I don't have time in the foreseeable future to really dig into this myself though.

**Comment by burke** [comment]
Stale, closing. Reopen if there's something we need to do still.
