### ISSUE TITLE
documentation - how does this interact with spring?

### ISSUE THREAD

**Issue by ConfusedVorlon** [Shopify/bootsnap#94]
I just heard about bootsnap, and it seems interesting.
I'm currently using spring.

what is the interaction?

get rid of spring?
use both?

it would be great to mention this in the readme or wiki

**Comment by rafaelfranca** [comment]
They are ortogonal tools. Springs caches your application so you don't need to start it every time you run a command, while bootsnap make the boot faster.

You can use both if you want and this is what a new generated rails application is going to use now.

**Comment by ConfusedVorlon** [comment]
Thanks for the response. Worth a mention in the readme?

**Comment by rafaelfranca** [comment]
Yeah, maybe. Can you open a PR?

**Comment by ConfusedVorlon** [comment]
sent
